import { ImageSourcePropType } from 'react-native';

export type UiIconKey =
  | 'ui_achievements'
  | 'ui_ad'
  | 'ui_aura'
  | 'ui_back'
  | 'ui_boss'
  | 'ui_chest_common'
  | 'ui_chest_epic'
  | 'ui_chest_legendary'
  | 'ui_chest_rare'
  | 'ui_coin'
  | 'ui_daily_reward'
  | 'ui_effect'
  | 'ui_event'
  | 'ui_fragments'
  | 'ui_gem'
  | 'ui_infinite'
  | 'ui_inventory'
  | 'ui_key'
  | 'ui_league_neon'
  | 'ui_legendary_key'
  | 'ui_locked'
  | 'ui_menu'
  | 'ui_missions'
  | 'ui_mute_on'
  | 'ui_mute_off'
  | 'ui_no_ads'
  | 'ui_play'
  | 'ui_profile'
  | 'ui_camera'
  | 'ui_remove_image'
  | 'ui_profile_frame'
  | 'ui_damage'
  | 'ui_speed'
  | 'ui_crit'
  | 'ui_xp'
  | 'ui_perfect'
  | 'ui_freeze'
  | 'ui_poison'
  | 'ui_burn'
  | 'ui_shock'
  | 'ui_repulse'
  | 'ui_pierce'
  | 'ui_area'
  | 'ui_gravity'
  | 'ui_combo'
  | 'ui_settings'
  | 'ui_skins'
  | 'ui_store'
  | 'ui_trail'
  | 'ui_upgrades'
  | 'ui_wheel';

export const UI_ICON_ASSETS: Partial<Record<UiIconKey, ImageSourcePropType>> = {
  ui_achievements: require('../../assets/ui/ui_achievements.png'),
  ui_ad: require('../../assets/ui/ui_ad.png'),
  ui_aura: require('../../assets/ui/ui_aura.png'),
  ui_back: require('../../assets/ui/ui_back.png'),
  ui_boss: require('../../assets/ui/ui_boss.png'),
  ui_chest_common: require('../../assets/ui/ui_chest_common.png'),
  ui_chest_epic: require('../../assets/ui/ui_chest_epic.png'),
  ui_chest_legendary: require('../../assets/ui/ui_chest_legendary.png'),
  ui_chest_rare: require('../../assets/ui/ui_chest_rare.png'),
  ui_coin: require('../../assets/ui/ui_coin.png'),
  ui_daily_reward: require('../../assets/ui/ui_daily_reward.png'),
  ui_effect: require('../../assets/ui/ui_effect.png'),
  ui_event: require('../../assets/ui/ui_event.png'),
  ui_fragments: require('../../assets/ui/ui_fragments.png'),
  ui_gem: require('../../assets/ui/ui_gem.png'),
  ui_infinite: require('../../assets/ui/ui_infinite.png'),
  ui_inventory: require('../../assets/ui/ui_inventory.png'),
  ui_key: require('../../assets/ui/ui_key.png'),
  ui_league_neon: require('../../assets/ui/ui_league_neon.png'),
  ui_legendary_key: require('../../assets/ui/ui_legendary_key.png'),
  ui_locked: require('../../assets/ui/ui_locked.png'),
  ui_menu: require('../../assets/ui/ui_menu.png'),
  ui_missions: require('../../assets/ui/ui_missions.png'),
  ui_mute_on: require('../../assets/ui/ui_mute_on.png'),
  ui_mute_off: require('../../assets/ui/ui_mute_off.png'),
  ui_no_ads: require('../../assets/ui/ui_no_ads.png'),
  ui_play: require('../../assets/ui/ui_play.png'),
  ui_profile: require('../../assets/ui/ui_profile.png'),
  ui_camera: require('../../assets/ui/ui_camera.png'),
  ui_remove_image: require('../../assets/ui/ui_remove_image.png'),
  ui_profile_frame: require('../../assets/ui/ui_profile_frame.png'),
  ui_damage: require('../../assets/ui/ui_damage.png'),
  ui_speed: require('../../assets/ui/ui_speed.png'),
  ui_crit: require('../../assets/ui/ui_crit.png'),
  ui_xp: require('../../assets/ui/ui_xp.png'),
  ui_perfect: require('../../assets/ui/ui_perfect.png'),
  ui_freeze: require('../../assets/ui/ui_freeze.png'),
  ui_poison: require('../../assets/ui/ui_poison.png'),
  ui_burn: require('../../assets/ui/ui_burn.png'),
  ui_shock: require('../../assets/ui/ui_shock.png'),
  ui_repulse: require('../../assets/ui/ui_repulse.png'),
  ui_pierce: require('../../assets/ui/ui_pierce.png'),
  ui_area: require('../../assets/ui/ui_area.png'),
  ui_gravity: require('../../assets/ui/ui_gravity.png'),
  ui_combo: require('../../assets/ui/ui_combo.png'),
  ui_settings: require('../../assets/ui/ui_settings.png'),
  ui_skins: require('../../assets/ui/ui_skins.png'),
  ui_store: require('../../assets/ui/ui_store.png'),
  ui_trail: require('../../assets/ui/ui_trail.png'),
  ui_upgrades: require('../../assets/ui/ui_upgrades.png'),
  ui_wheel: require('../../assets/ui/ui_wheel.png'),
};
