import type { TranslationKey } from './en';

export const de: Partial<Record<TranslationKey, string>> = {
  'common.back': 'Zurück', 'common.buy': 'Kaufen', 'common.cancel': 'Abbrechen', 'common.close': 'Schließen', 'common.collect': 'Abholen', 'common.confirm': 'Bestätigen', 'common.cost': 'Kosten', 'common.current': 'Aktuell', 'common.exit': 'Beenden', 'common.loading': 'Lädt...', 'common.locked': 'Gesperrt', 'common.menu': 'Menü', 'common.next': 'Weiter', 'common.open': 'Öffnen', 'common.save': 'Speichern', 'common.select': 'Auswählen', 'common.unavailable': 'Nicht verfügbar', 'common.unlock': 'Freischalten', 'common.upgrade': 'Verbessern',
  'nav.achievements': 'Erfolge', 'nav.boss': 'Boss', 'nav.dailyReward': 'Tägliche Belohnung', 'nav.event': 'Event', 'nav.infinite': 'Endlos', 'nav.inventory': 'Inventar', 'nav.missions': 'Missionen', 'nav.more': 'Mehr', 'nav.neonLeague': 'Neon-Liga', 'nav.play': 'Spielen', 'nav.profile': 'Profil', 'nav.settings': 'Einstellungen', 'nav.shop': 'Shop', 'nav.skins': 'Skins', 'nav.upgrades': 'Upgrades', 'nav.wheel': 'Rad',
  'home.achievementUnlocked': 'Erfolg freigeschaltet', 'home.offlineAway': 'Du warst {{hours}}h weg.', 'home.offlineBonus': 'Aktiver Bonus: {{bonus}}', 'home.offlineReward': 'Offline-Belohnung',
  'game.chooseUpgrade': 'Upgrade wählen', 'game.combo': 'Combo', 'game.defeat': 'Niederlage', 'game.gameOver': 'Game Over', 'game.level': 'Level', 'game.pause': 'Pause', 'game.perfect': 'Perfekt', 'game.reroll': 'Neu würfeln', 'game.rerollWithDiamonds': 'Mit Diamanten neu würfeln', 'game.resume': 'Fortsetzen', 'game.victory': 'Sieg',
  'stats.chests': 'Truhen', 'stats.coins': 'Münzen', 'stats.damage': 'Schaden', 'stats.diamonds': 'Diamanten', 'stats.gold': 'Gold', 'stats.keys': 'Schlüssel', 'stats.speed': 'Tempo', 'stats.xp': 'XP',
  'upgrades.cashGain': 'Geldgewinn', 'upgrades.critChance': 'Krit-Chance', 'upgrades.maxLevel': 'Max. Level', 'upgrades.perfectChance': 'Perfekt-Chance', 'upgrades.permanent': 'Permanente Upgrades', 'upgrades.ringRepulse': 'Ring-Rückstoß', 'upgrades.slowRings': 'Langsame Ringe', 'upgrades.xpBoost': 'XP-Boost', 'errors.notEnoughCoins': 'Nicht genug Münzen', 'errors.notEnoughDiamonds': 'Nicht genug Diamanten',
  'shop.chestPack': 'Truhenpaket', 'shop.dailyOffer': 'Tagesangebot', 'shop.eventPack': 'Eventpaket', 'shop.fragmentPack': 'Fragmentpaket', 'shop.freeChest': 'Gratis-Truhe', 'shop.largeDiamondPack': 'Großes Diamantenpaket', 'shop.mediumDiamondPack': 'Mittleres Diamantenpaket', 'shop.purchased': 'Gekauft', 'shop.removeAds': 'Werbung entfernen', 'shop.reward': 'Belohnung', 'shop.skinPack': 'Skinpaket', 'shop.smallDiamondPack': 'Kleines Diamantenpaket', 'shop.starterPack': 'Starterpaket',
  'inventory.empty': 'Inventar leer', 'inventory.openChest': 'Truhe öffnen', 'inventory.rewards': 'Belohnungen', 'inventory.youReceived': 'Du hast erhalten',
  'profile.bestScore': 'Beste Punktzahl', 'profile.changeAvatar': 'Avatar ändern', 'profile.choosePhoto': 'Foto wählen', 'profile.matchesPlayed': 'Gespielte Matches', 'profile.photoPermissionMessage': 'Erlaube den Galeriezugriff, um ein Profilfoto auszuwählen.', 'profile.photoPermissionTitle': 'Berechtigung erforderlich', 'profile.removePhoto': 'Foto entfernen', 'profile.statistics': 'Statistiken', 'profile.totalCoins': 'Münzen gesamt', 'profile.account': 'Konto', 'profile.favoriteSkin': 'Lieblingsskin', 'profile.saveNick': 'Namen speichern',
  'settings.language': 'Sprache', 'settings.music': 'Musik', 'settings.mute': 'Stumm', 'settings.privacyPolicy': 'Datenschutzrichtlinie', 'settings.selectLanguage': 'Sprache auswählen', 'settings.sound': 'Sound', 'settings.support': 'Support', 'settings.unmute': 'Ton an', 'settings.effects': 'Effekte', 'settings.master': 'Alles',
  'purchase.canceled': 'Kauf abgebrochen', 'purchase.failed': 'Kauf fehlgeschlagen', 'purchase.processing': 'Kauf wird verarbeitet', 'purchase.restore': 'Käufe wiederherstellen', 'purchase.restored': 'Kauf wiederhergestellt', 'purchase.successful': 'Kauf erfolgreich', 'purchase.unavailable': 'Kauf nicht verfügbar',
  'ads.closed': 'Anzeige geschlossen', 'ads.doubleAd': 'Verdoppeln - Anzeige', 'ads.loading': 'Anzeige lädt', 'ads.rewardGranted': 'Belohnung gewährt', 'ads.tryAgainLater': 'Später erneut versuchen', 'ads.unavailable': 'Anzeige nicht verfügbar', 'ads.watchAd': 'Anzeige ansehen', 'ads.watchToReceive': 'Anzeige ansehen, um Belohnung zu erhalten', 'ads.watchVideo': 'Video ansehen',
};
