import type { TranslationKey } from './en';

export const es: Partial<Record<TranslationKey, string>> = {
  'common.back': 'Atrás', 'common.buy': 'Comprar', 'common.cancel': 'Cancelar', 'common.close': 'Cerrar', 'common.collect': 'Recoger', 'common.confirm': 'Confirmar', 'common.cost': 'Costo', 'common.current': 'Actual', 'common.exit': 'Salir', 'common.loading': 'Cargando...', 'common.locked': 'Bloqueado', 'common.menu': 'Menú', 'common.next': 'Siguiente', 'common.open': 'Abrir', 'common.save': 'Guardar', 'common.select': 'Seleccionar', 'common.unavailable': 'No disponible', 'common.unlock': 'Desbloquear', 'common.upgrade': 'Mejorar',
  'nav.achievements': 'Logros', 'nav.boss': 'Jefe', 'nav.dailyReward': 'Recompensa diaria', 'nav.event': 'Evento', 'nav.infinite': 'Infinito', 'nav.inventory': 'Inventario', 'nav.missions': 'Misiones', 'nav.more': 'Más', 'nav.neonLeague': 'Liga Neon', 'nav.play': 'Jugar', 'nav.profile': 'Perfil', 'nav.settings': 'Ajustes', 'nav.shop': 'Tienda', 'nav.skins': 'Skins', 'nav.upgrades': 'Mejoras', 'nav.wheel': 'Ruleta',
  'home.achievementUnlocked': 'Logro desbloqueado', 'home.offlineAway': 'Estuviste fuera {{hours}}h.', 'home.offlineBonus': 'Bono activo: {{bonus}}', 'home.offlineReward': 'Recompensa offline',
  'game.chooseUpgrade': 'Elige una mejora', 'game.combo': 'Combo', 'game.defeat': 'Derrota', 'game.gameOver': 'Fin del juego', 'game.level': 'Nivel', 'game.pause': 'Pausa', 'game.perfect': 'Perfecto', 'game.reroll': 'Cambiar', 'game.rerollWithDiamonds': 'Cambiar con diamantes', 'game.resume': 'Continuar', 'game.victory': 'Victoria',
  'stats.chests': 'Cofres', 'stats.coins': 'Monedas', 'stats.damage': 'Daño', 'stats.diamonds': 'Diamantes', 'stats.gold': 'Oro', 'stats.keys': 'Llaves', 'stats.speed': 'Velocidad', 'stats.xp': 'XP',
  'upgrades.cashGain': 'Ganancia de dinero', 'upgrades.critChance': 'Prob. crítica', 'upgrades.maxLevel': 'Nivel máximo', 'upgrades.perfectChance': 'Prob. perfecta', 'upgrades.permanent': 'Mejoras permanentes', 'upgrades.ringRepulse': 'Repulsión de anillos', 'upgrades.slowRings': 'Anillos lentos', 'upgrades.xpBoost': 'Bono de XP', 'errors.notEnoughCoins': 'No hay suficientes monedas', 'errors.notEnoughDiamonds': 'No hay suficientes diamantes',
  'shop.chestPack': 'Paquete de cofres', 'shop.dailyOffer': 'Oferta diaria', 'shop.eventPack': 'Paquete de evento', 'shop.fragmentPack': 'Paquete de fragmentos', 'shop.freeChest': 'Cofre gratis', 'shop.largeDiamondPack': 'Paquete grande de diamantes', 'shop.mediumDiamondPack': 'Paquete mediano de diamantes', 'shop.purchased': 'Comprado', 'shop.removeAds': 'Quitar anuncios', 'shop.reward': 'Recompensa', 'shop.skinPack': 'Paquete de skins', 'shop.smallDiamondPack': 'Paquete pequeño de diamantes', 'shop.starterPack': 'Paquete inicial',
  'inventory.empty': 'Inventario vacío', 'inventory.openChest': 'Abrir cofre', 'inventory.rewards': 'Recompensas', 'inventory.youReceived': 'Recibiste',
  'profile.bestScore': 'Mejor puntuación', 'profile.changeAvatar': 'Cambiar avatar', 'profile.choosePhoto': 'Elegir foto', 'profile.matchesPlayed': 'Partidas jugadas', 'profile.photoPermissionMessage': 'Permite acceso a la galería para elegir una foto de perfil.', 'profile.photoPermissionTitle': 'Permiso necesario', 'profile.removePhoto': 'Quitar foto', 'profile.statistics': 'Estadísticas', 'profile.totalCoins': 'Monedas totales', 'profile.account': 'Cuenta', 'profile.favoriteSkin': 'Skin favorita', 'profile.saveNick': 'Guardar nick',
  'settings.language': 'Idioma', 'settings.music': 'Música', 'settings.mute': 'Silenciar', 'settings.privacyPolicy': 'Política de privacidad', 'settings.selectLanguage': 'Seleccionar idioma', 'settings.sound': 'Sonido', 'settings.support': 'Soporte', 'settings.unmute': 'Activar sonido', 'settings.effects': 'Efectos', 'settings.master': 'Todo',
  'purchase.canceled': 'Compra cancelada', 'purchase.failed': 'Compra fallida', 'purchase.processing': 'Procesando compra', 'purchase.restore': 'Restaurar compras', 'purchase.restored': 'Compra restaurada', 'purchase.successful': 'Compra exitosa', 'purchase.unavailable': 'Compra no disponible',
  'ads.closed': 'Anuncio cerrado', 'ads.doubleAd': 'Duplicar - Anuncio', 'ads.loading': 'Cargando anuncio', 'ads.rewardGranted': 'Recompensa otorgada', 'ads.tryAgainLater': 'Inténtalo más tarde', 'ads.unavailable': 'Anuncio no disponible', 'ads.watchAd': 'Ver anuncio', 'ads.watchToReceive': 'Ver anuncio para recibir recompensa', 'ads.watchVideo': 'Ver video',
};
