import type { TranslationKey } from './en';

export const fr: Partial<Record<TranslationKey, string>> = {
  'common.back': 'Retour', 'common.buy': 'Acheter', 'common.cancel': 'Annuler', 'common.close': 'Fermer', 'common.collect': 'Récupérer', 'common.confirm': 'Confirmer', 'common.cost': 'Coût', 'common.current': 'Actuel', 'common.exit': 'Quitter', 'common.loading': 'Chargement...', 'common.locked': 'Verrouillé', 'common.menu': 'Menu', 'common.next': 'Suivant', 'common.open': 'Ouvrir', 'common.save': 'Enregistrer', 'common.select': 'Sélectionner', 'common.unavailable': 'Indisponible', 'common.unlock': 'Déverrouiller', 'common.upgrade': 'Améliorer',
  'nav.achievements': 'Succès', 'nav.boss': 'Boss', 'nav.dailyReward': 'Récompense quotidienne', 'nav.event': 'Événement', 'nav.infinite': 'Infini', 'nav.inventory': 'Inventaire', 'nav.missions': 'Missions', 'nav.more': 'Plus', 'nav.neonLeague': 'Ligue Neon', 'nav.play': 'Jouer', 'nav.profile': 'Profil', 'nav.settings': 'Paramètres', 'nav.shop': 'Boutique', 'nav.skins': 'Skins', 'nav.upgrades': 'Améliorations', 'nav.wheel': 'Roue',
  'home.achievementUnlocked': 'Succès déverrouillé', 'home.offlineAway': 'Vous étiez absent pendant {{hours}}h.', 'home.offlineBonus': 'Bonus actif : {{bonus}}', 'home.offlineReward': 'Récompense hors ligne',
  'game.chooseUpgrade': 'Choisissez une amélioration', 'game.combo': 'Combo', 'game.defeat': 'Défaite', 'game.gameOver': 'Fin de partie', 'game.level': 'Niveau', 'game.pause': 'Pause', 'game.perfect': 'Parfait', 'game.reroll': 'Relancer', 'game.rerollWithDiamonds': 'Relancer avec des diamants', 'game.resume': 'Reprendre', 'game.victory': 'Victoire',
  'stats.chests': 'Coffres', 'stats.coins': 'Pièces', 'stats.damage': 'Dégâts', 'stats.diamonds': 'Diamants', 'stats.gold': 'Or', 'stats.keys': 'Clés', 'stats.speed': 'Vitesse', 'stats.xp': 'XP',
  'upgrades.cashGain': 'Gain d’argent', 'upgrades.critChance': 'Chance critique', 'upgrades.maxLevel': 'Niveau max', 'upgrades.perfectChance': 'Chance parfaite', 'upgrades.permanent': 'Améliorations permanentes', 'upgrades.ringRepulse': 'Répulsion des anneaux', 'upgrades.slowRings': 'Anneaux ralentis', 'upgrades.xpBoost': 'Boost XP', 'errors.notEnoughCoins': 'Pas assez de pièces', 'errors.notEnoughDiamonds': 'Pas assez de diamants',
  'shop.chestPack': 'Pack de coffres', 'shop.dailyOffer': 'Offre quotidienne', 'shop.eventPack': 'Pack événement', 'shop.fragmentPack': 'Pack de fragments', 'shop.freeChest': 'Coffre gratuit', 'shop.largeDiamondPack': 'Grand pack de diamants', 'shop.mediumDiamondPack': 'Pack moyen de diamants', 'shop.purchased': 'Acheté', 'shop.removeAds': 'Supprimer les pubs', 'shop.reward': 'Récompense', 'shop.skinPack': 'Pack de skins', 'shop.smallDiamondPack': 'Petit pack de diamants', 'shop.starterPack': 'Pack de départ',
  'inventory.empty': 'Inventaire vide', 'inventory.openChest': 'Ouvrir le coffre', 'inventory.rewards': 'Récompenses', 'inventory.youReceived': 'Vous avez reçu',
  'profile.bestScore': 'Meilleur score', 'profile.changeAvatar': 'Changer d’avatar', 'profile.choosePhoto': 'Choisir une photo', 'profile.matchesPlayed': 'Parties jouées', 'profile.photoPermissionMessage': 'Autorisez l’accès à la galerie pour choisir une photo de profil.', 'profile.photoPermissionTitle': 'Autorisation requise', 'profile.removePhoto': 'Supprimer la photo', 'profile.statistics': 'Statistiques', 'profile.totalCoins': 'Pièces totales', 'profile.account': 'Compte', 'profile.favoriteSkin': 'Skin favori', 'profile.saveNick': 'Enregistrer le pseudo',
  'settings.language': 'Langue', 'settings.music': 'Musique', 'settings.mute': 'Muet', 'settings.privacyPolicy': 'Politique de confidentialité', 'settings.selectLanguage': 'Choisir la langue', 'settings.sound': 'Son', 'settings.support': 'Support', 'settings.unmute': 'Activer le son', 'settings.effects': 'Effets', 'settings.master': 'Tout',
  'purchase.canceled': 'Achat annulé', 'purchase.failed': 'Achat échoué', 'purchase.processing': 'Traitement de l’achat', 'purchase.restore': 'Restaurer les achats', 'purchase.restored': 'Achat restauré', 'purchase.successful': 'Achat réussi', 'purchase.unavailable': 'Achat indisponible',
  'ads.closed': 'Pub fermée', 'ads.doubleAd': 'Doubler - Pub', 'ads.loading': 'Chargement de la pub', 'ads.rewardGranted': 'Récompense accordée', 'ads.tryAgainLater': 'Réessayez plus tard', 'ads.unavailable': 'Pub indisponible', 'ads.watchAd': 'Regarder la pub', 'ads.watchToReceive': 'Regarder une pub pour recevoir la récompense', 'ads.watchVideo': 'Regarder la vidéo',
};
