import type { TranslationKey } from './en';

export const ja: Partial<Record<TranslationKey, string>> = {
  'common.back': '戻る', 'common.buy': '購入', 'common.cancel': 'キャンセル', 'common.close': '閉じる', 'common.collect': '受け取る', 'common.confirm': '確認', 'common.cost': 'コスト', 'common.current': '現在', 'common.exit': '終了', 'common.loading': '読み込み中...', 'common.locked': 'ロック中', 'common.menu': 'メニュー', 'common.next': '次', 'common.open': '開く', 'common.save': '保存', 'common.select': '選択', 'common.unavailable': '利用不可', 'common.unlock': '解除', 'common.upgrade': '強化',
  'nav.achievements': '実績', 'nav.boss': 'ボス', 'nav.dailyReward': 'デイリー報酬', 'nav.event': 'イベント', 'nav.infinite': '無限', 'nav.inventory': 'インベントリ', 'nav.missions': 'ミッション', 'nav.more': 'その他', 'nav.neonLeague': 'ネオンリーグ', 'nav.play': 'プレイ', 'nav.profile': 'プロフィール', 'nav.settings': '設定', 'nav.shop': 'ショップ', 'nav.skins': 'スキン', 'nav.upgrades': '強化', 'nav.wheel': 'ルーレット',
  'home.achievementUnlocked': '実績解除', 'home.offlineAway': '{{hours}}時間離れていました。', 'home.offlineBonus': '有効ボーナス: {{bonus}}', 'home.offlineReward': 'オフライン報酬',
  'game.chooseUpgrade': '強化を選択', 'game.combo': 'コンボ', 'game.defeat': '敗北', 'game.gameOver': 'ゲームオーバー', 'game.level': 'レベル', 'game.pause': '一時停止', 'game.perfect': 'パーフェクト', 'game.reroll': '引き直し', 'game.rerollWithDiamonds': 'ダイヤで引き直し', 'game.resume': '再開', 'game.victory': '勝利',
  'stats.chests': '宝箱', 'stats.coins': 'コイン', 'stats.damage': 'ダメージ', 'stats.diamonds': 'ダイヤ', 'stats.gold': 'ゴールド', 'stats.keys': '鍵', 'stats.speed': '速度', 'stats.xp': 'XP',
  'upgrades.cashGain': '獲得コイン', 'upgrades.critChance': '会心率', 'upgrades.maxLevel': '最大レベル', 'upgrades.perfectChance': 'パーフェクト率', 'upgrades.permanent': '永久強化', 'upgrades.ringRepulse': 'リング反発', 'upgrades.slowRings': 'リング減速', 'upgrades.xpBoost': 'XPボーナス', 'errors.notEnoughCoins': 'コインが足りません', 'errors.notEnoughDiamonds': 'ダイヤが足りません',
  'shop.chestPack': '宝箱パック', 'shop.dailyOffer': 'デイリーオファー', 'shop.eventPack': 'イベントパック', 'shop.fragmentPack': '欠片パック', 'shop.freeChest': '無料宝箱', 'shop.largeDiamondPack': '大型ダイヤパック', 'shop.mediumDiamondPack': '中型ダイヤパック', 'shop.purchased': '購入済み', 'shop.removeAds': '広告削除', 'shop.reward': '報酬', 'shop.skinPack': 'スキンパック', 'shop.smallDiamondPack': '小型ダイヤパック', 'shop.starterPack': 'スターターパック',
  'inventory.empty': 'インベントリは空です', 'inventory.openChest': '宝箱を開く', 'inventory.rewards': '報酬', 'inventory.youReceived': '獲得しました',
  'profile.bestScore': 'ベストスコア', 'profile.changeAvatar': 'アバター変更', 'profile.choosePhoto': '写真を選択', 'profile.matchesPlayed': 'プレイ回数', 'profile.photoPermissionMessage': 'プロフィール写真を選ぶためにギャラリーへのアクセスを許可してください。', 'profile.photoPermissionTitle': '権限が必要です', 'profile.removePhoto': '写真を削除', 'profile.statistics': '統計', 'profile.totalCoins': '合計コイン', 'profile.account': 'アカウント', 'profile.favoriteSkin': 'お気に入りスキン', 'profile.saveNick': '名前を保存',
  'settings.language': '言語', 'settings.music': '音楽', 'settings.mute': 'ミュート', 'settings.privacyPolicy': 'プライバシーポリシー', 'settings.selectLanguage': '言語を選択', 'settings.sound': 'サウンド', 'settings.support': 'サポート', 'settings.unmute': 'ミュート解除', 'settings.effects': '効果音', 'settings.master': 'すべて',
  'purchase.canceled': '購入をキャンセルしました', 'purchase.failed': '購入に失敗しました', 'purchase.processing': '購入処理中', 'purchase.restore': '購入を復元', 'purchase.restored': '購入を復元しました', 'purchase.successful': '購入成功', 'purchase.unavailable': '購入できません',
  'ads.closed': '広告を閉じました', 'ads.doubleAd': '2倍 - 広告', 'ads.loading': '広告読み込み中', 'ads.rewardGranted': '報酬を受け取りました', 'ads.tryAgainLater': '後でもう一度お試しください', 'ads.unavailable': '広告は利用不可', 'ads.watchAd': '広告を見る', 'ads.watchToReceive': '広告を見て報酬を受け取る', 'ads.watchVideo': '動画を見る',
};
