import type { TranslationKey } from './en';

export const ko: Partial<Record<TranslationKey, string>> = {
  'common.back': '뒤로', 'common.buy': '구매', 'common.cancel': '취소', 'common.close': '닫기', 'common.collect': '받기', 'common.confirm': '확인', 'common.cost': '비용', 'common.current': '현재', 'common.exit': '나가기', 'common.loading': '불러오는 중...', 'common.locked': '잠김', 'common.menu': '메뉴', 'common.next': '다음', 'common.open': '열기', 'common.save': '저장', 'common.select': '선택', 'common.unavailable': '사용 불가', 'common.unlock': '해제', 'common.upgrade': '업그레이드',
  'nav.achievements': '업적', 'nav.boss': '보스', 'nav.dailyReward': '일일 보상', 'nav.event': '이벤트', 'nav.infinite': '무한', 'nav.inventory': '인벤토리', 'nav.missions': '미션', 'nav.more': '더보기', 'nav.neonLeague': '네온 리그', 'nav.play': '플레이', 'nav.profile': '프로필', 'nav.settings': '설정', 'nav.shop': '상점', 'nav.skins': '스킨', 'nav.upgrades': '업그레이드', 'nav.wheel': '룰렛',
  'home.achievementUnlocked': '업적 달성', 'home.offlineAway': '{{hours}}시간 동안 자리를 비웠습니다.', 'home.offlineBonus': '활성 보너스: {{bonus}}', 'home.offlineReward': '오프라인 보상',
  'game.chooseUpgrade': '업그레이드 선택', 'game.combo': '콤보', 'game.defeat': '패배', 'game.gameOver': '게임 오버', 'game.level': '레벨', 'game.pause': '일시정지', 'game.perfect': '퍼펙트', 'game.reroll': '다시 뽑기', 'game.rerollWithDiamonds': '다이아로 다시 뽑기', 'game.resume': '계속', 'game.victory': '승리',
  'stats.chests': '상자', 'stats.coins': '코인', 'stats.damage': '피해', 'stats.diamonds': '다이아', 'stats.gold': '골드', 'stats.keys': '열쇠', 'stats.speed': '속도', 'stats.xp': 'XP',
  'upgrades.cashGain': '현금 획득', 'upgrades.critChance': '치명타 확률', 'upgrades.maxLevel': '최대 레벨', 'upgrades.perfectChance': '퍼펙트 확률', 'upgrades.permanent': '영구 업그레이드', 'upgrades.ringRepulse': '링 밀치기', 'upgrades.slowRings': '느린 링', 'upgrades.xpBoost': 'XP 부스트', 'errors.notEnoughCoins': '코인이 부족합니다', 'errors.notEnoughDiamonds': '다이아가 부족합니다',
  'shop.chestPack': '상자 팩', 'shop.dailyOffer': '일일 상품', 'shop.eventPack': '이벤트 팩', 'shop.fragmentPack': '조각 팩', 'shop.freeChest': '무료 상자', 'shop.largeDiamondPack': '대형 다이아 팩', 'shop.mediumDiamondPack': '중형 다이아 팩', 'shop.purchased': '구매됨', 'shop.removeAds': '광고 제거', 'shop.reward': '보상', 'shop.skinPack': '스킨 팩', 'shop.smallDiamondPack': '소형 다이아 팩', 'shop.starterPack': '스타터 팩',
  'inventory.empty': '인벤토리가 비었습니다', 'inventory.openChest': '상자 열기', 'inventory.rewards': '보상', 'inventory.youReceived': '획득했습니다',
  'profile.bestScore': '최고 점수', 'profile.changeAvatar': '아바타 변경', 'profile.choosePhoto': '사진 선택', 'profile.matchesPlayed': '플레이 횟수', 'profile.photoPermissionMessage': '프로필 사진을 선택하려면 갤러리 접근을 허용하세요.', 'profile.photoPermissionTitle': '권한 필요', 'profile.removePhoto': '사진 제거', 'profile.statistics': '통계', 'profile.totalCoins': '총 코인', 'profile.account': '계정', 'profile.favoriteSkin': '즐겨찾는 스킨', 'profile.saveNick': '닉네임 저장',
  'settings.language': '언어', 'settings.music': '음악', 'settings.mute': '음소거', 'settings.privacyPolicy': '개인정보 처리방침', 'settings.selectLanguage': '언어 선택', 'settings.sound': '소리', 'settings.support': '지원', 'settings.unmute': '음소거 해제', 'settings.effects': '효과음', 'settings.master': '전체',
  'purchase.canceled': '구매가 취소되었습니다', 'purchase.failed': '구매 실패', 'purchase.processing': '구매 처리 중', 'purchase.restore': '구매 복원', 'purchase.restored': '구매가 복원되었습니다', 'purchase.successful': '구매 성공', 'purchase.unavailable': '구매 불가',
  'ads.closed': '광고 닫힘', 'ads.doubleAd': '2배 - 광고', 'ads.loading': '광고 로딩 중', 'ads.rewardGranted': '보상 지급됨', 'ads.tryAgainLater': '나중에 다시 시도하세요', 'ads.unavailable': '광고 사용 불가', 'ads.watchAd': '광고 보기', 'ads.watchToReceive': '광고를 보고 보상 받기', 'ads.watchVideo': '동영상 보기',
};
