import type { TranslationKey } from './en';

export const zhCN: Partial<Record<TranslationKey, string>> = {
  'common.back': '返回', 'common.buy': '购买', 'common.cancel': '取消', 'common.close': '关闭', 'common.collect': '领取', 'common.confirm': '确认', 'common.cost': '花费', 'common.current': '当前', 'common.exit': '退出', 'common.loading': '加载中...', 'common.locked': '已锁定', 'common.menu': '菜单', 'common.next': '下一级', 'common.open': '打开', 'common.save': '保存', 'common.select': '选择', 'common.unavailable': '不可用', 'common.unlock': '解锁', 'common.upgrade': '升级',
  'nav.achievements': '成就', 'nav.boss': 'Boss', 'nav.dailyReward': '每日奖励', 'nav.event': '活动', 'nav.infinite': '无限', 'nav.inventory': '背包', 'nav.missions': '任务', 'nav.more': '更多', 'nav.neonLeague': '霓虹联赛', 'nav.play': '开始', 'nav.profile': '资料', 'nav.settings': '设置', 'nav.shop': '商店', 'nav.skins': '皮肤', 'nav.upgrades': '升级', 'nav.wheel': '转盘',
  'home.achievementUnlocked': '成就已解锁', 'home.offlineAway': '你离线了 {{hours}} 小时。', 'home.offlineBonus': '当前加成：{{bonus}}', 'home.offlineReward': '离线奖励',
  'game.chooseUpgrade': '选择一项升级', 'game.combo': '连击', 'game.defeat': '失败', 'game.gameOver': '游戏结束', 'game.level': '等级', 'game.pause': '暂停', 'game.perfect': '完美', 'game.reroll': '重抽', 'game.rerollWithDiamonds': '用钻石重抽', 'game.resume': '继续', 'game.victory': '胜利',
  'stats.chests': '宝箱', 'stats.coins': '金币', 'stats.damage': '伤害', 'stats.diamonds': '钻石', 'stats.gold': '金子', 'stats.keys': '钥匙', 'stats.speed': '速度', 'stats.xp': '经验',
  'upgrades.cashGain': '金币收益', 'upgrades.critChance': '暴击率', 'upgrades.maxLevel': '最高等级', 'upgrades.perfectChance': '完美率', 'upgrades.permanent': '永久升级', 'upgrades.ringRepulse': '圆环击退', 'upgrades.slowRings': '减速圆环', 'upgrades.xpBoost': '经验加成', 'errors.notEnoughCoins': '金币不足', 'errors.notEnoughDiamonds': '钻石不足',
  'shop.chestPack': '宝箱包', 'shop.dailyOffer': '每日优惠', 'shop.eventPack': '活动包', 'shop.fragmentPack': '碎片包', 'shop.freeChest': '免费宝箱', 'shop.largeDiamondPack': '大钻石包', 'shop.mediumDiamondPack': '中钻石包', 'shop.purchased': '已购买', 'shop.removeAds': '移除广告', 'shop.reward': '奖励', 'shop.skinPack': '皮肤包', 'shop.smallDiamondPack': '小钻石包', 'shop.starterPack': '新手包',
  'inventory.empty': '背包为空', 'inventory.openChest': '打开宝箱', 'inventory.rewards': '奖励', 'inventory.youReceived': '你获得了',
  'profile.bestScore': '最高分', 'profile.changeAvatar': '更换头像', 'profile.choosePhoto': '选择照片', 'profile.matchesPlayed': '已玩局数', 'profile.photoPermissionMessage': '请允许访问图库以选择头像照片。', 'profile.photoPermissionTitle': '需要权限', 'profile.removePhoto': '移除照片', 'profile.statistics': '统计', 'profile.totalCoins': '总金币', 'profile.account': '账号', 'profile.favoriteSkin': '最爱皮肤', 'profile.saveNick': '保存昵称',
  'settings.language': '语言', 'settings.music': '音乐', 'settings.mute': '静音', 'settings.privacyPolicy': '隐私政策', 'settings.selectLanguage': '选择语言', 'settings.sound': '声音', 'settings.support': '支持', 'settings.unmute': '取消静音', 'settings.effects': '音效', 'settings.master': '全部',
  'purchase.canceled': '购买已取消', 'purchase.failed': '购买失败', 'purchase.processing': '正在处理购买', 'purchase.restore': '恢复购买', 'purchase.restored': '购买已恢复', 'purchase.successful': '购买成功', 'purchase.unavailable': '购买不可用',
  'ads.closed': '广告已关闭', 'ads.doubleAd': '翻倍 - 广告', 'ads.loading': '加载广告中', 'ads.rewardGranted': '奖励已发放', 'ads.tryAgainLater': '请稍后再试', 'ads.unavailable': '广告不可用', 'ads.watchAd': '观看广告', 'ads.watchToReceive': '观看广告领取奖励', 'ads.watchVideo': '观看视频',
};
