extends Node

signal language_changed(language: String)

const TEXT := {
	"en": {
		"back": "Back",
		"play": "Play",
		"upgrades": "Upgrades",
		"skins": "Skins",
		"shop": "Shop",
		"inventory": "Inventory",
		"missions": "Missions",
		"event": "Event",
		"wheel": "Wheel",
		"daily_reward": "Daily Reward",
		"boss": "Boss",
		"league": "Neon League",
		"achievements": "Achievements",
		"settings": "Settings",
		"profile": "Profile",
		"muted": "Muted",
		"audio_on": "Audio: On",
		"audio_off": "Audio: Muted",
		"language": "Language",
		"battle": "Battle",
		"quit": "Quit",
		"victory": "Victory",
		"defeat": "Defeat",
		"select": "Select",
		"locked": "Locked",
		"unlocked": "Unlocked",
		"close": "Close",
		"buy": "Buy",
		"open": "Open",
		"claim": "Claim",
		"done": "Done",
		"used": "Used",
		"watch_ad": "Watch Ad",
		"free": "Free",
		"spin": "Spin",
		"go": "Go",
		"wait": "Wait",
		"continue": "Continue",
		"unavailable": "Unavailable",
		"insufficient": "Not enough resources",
		"chests": "Chests",
		"diamonds": "Diamonds",
		"keys": "Keys",
		"rewards": "Rewards",
		"free_chest": "Free Chest",
		"inventory_empty": "Inventory is empty",
		"inventory_empty_desc": "Chests, keys and saved rewards will appear here.",
		"no_chests": "No stored chests",
		"stored_chests_desc": "Purchased or earned chests will appear in Inventory.",
		"stored_reward": "Stored reward. Open when ready.",
		"stored_item": "Stored item.",
		"reward_obtained": "Reward obtained",
		"achievement_unlocked": "Achievement unlocked",
		"claim_your_reward": "Claim your reward",
		"free_spin": "Free Spin",
		"mock_ad_spin": "Mock Ad Spin",
		"spin_desc": "Spin once per day for coins, diamonds, keys or chests.",
		"ad_spin_desc": "Prepared rewarded-ad flow. Uses a mock reward for now.",
		"missions_reward": "Reward",
		"progress": "Progress",
	},
	"pt": {
		"back": "Voltar",
		"play": "Jogar",
		"upgrades": "Melhorias",
		"skins": "Skins",
		"shop": "Loja",
		"inventory": "Inventário",
		"missions": "Missões",
		"event": "Evento",
		"wheel": "Roleta",
		"daily_reward": "Recompensa diária",
		"boss": "Boss",
		"league": "Liga Neon",
		"achievements": "Conquistas",
		"settings": "Configurações",
		"profile": "Perfil",
		"muted": "Mudo",
		"audio_on": "Áudio: Ligado",
		"audio_off": "Áudio: Mudo",
		"language": "Idioma",
		"battle": "Batalhar",
		"quit": "Sair",
		"victory": "Vitória",
		"defeat": "Derrota",
		"select": "Selecionar",
		"locked": "Bloqueado",
		"unlocked": "Liberado",
		"close": "Fechar",
		"buy": "Comprar",
		"open": "Abrir",
		"claim": "Coletar",
		"done": "Concluído",
		"used": "Usado",
		"watch_ad": "Ver anúncio",
		"free": "Grátis",
		"spin": "Girar",
		"go": "Ir",
		"wait": "Aguardar",
		"continue": "Continuar",
		"unavailable": "Indisponível",
		"insufficient": "Recurso insuficiente",
		"chests": "Baús",
		"diamonds": "Diamantes",
		"keys": "Chaves",
		"rewards": "Recompensas",
		"free_chest": "Baú grátis",
		"inventory_empty": "Inventário vazio",
		"inventory_empty_desc": "Baús, chaves e recompensas guardadas aparecerão aqui.",
		"no_chests": "Nenhum baú guardado",
		"stored_chests_desc": "Baús comprados ou ganhos aparecerão no Inventário.",
		"stored_reward": "Recompensa guardada. Abra quando quiser.",
		"stored_item": "Item guardado.",
		"reward_obtained": "Recompensa obtida",
		"achievement_unlocked": "Conquista desbloqueada",
		"claim_your_reward": "Colete sua recompensa",
		"free_spin": "Giro grátis",
		"mock_ad_spin": "Giro por anúncio",
		"spin_desc": "Gire uma vez por dia para ganhar moedas, diamantes, chaves ou baús.",
		"ad_spin_desc": "Fluxo preparado de anúncio recompensado. Usa recompensa mockada por enquanto.",
		"missions_reward": "Recompensa",
		"progress": "Progresso",
	},
}


func current_language() -> String:
	var language := "en"
	if has_node("/root/GameState"):
		language = String(GameState.data.get("settings", {}).get("language", "en"))
	return "pt" if language.begins_with("pt") else "en"


func tr_key(key: String, fallback := "") -> String:
	var language := current_language()
	return String(Dictionary(TEXT.get(language, {})).get(key, fallback if not fallback.is_empty() else key))


func set_language(language: String) -> void:
	var normalized := "pt" if language.begins_with("pt") else "en"
	if has_node("/root/GameState"):
		GameState.set_language(normalized)
	language_changed.emit(normalized)
