extends Node

# Dados mecanicamente portados da branch main (frontend/src/game).

const BASE_SKINS := [
	{ "id": "neon_blue", "name": "Neon Azul", "rarity": "common", "primary": "#00f0ff", "secondary": "#0088ff", "desc": "Esfera inicial equilibrada.", "passive": { "type": "perfect_chance", "value": 0.005 }, "trail": "Trail", "impact": "Impacto" },
	{ "id": "puppy", "name": "Cachorrinho", "rarity": "common", "primary": "#ffcc88", "secondary": "#8a5a32", "desc": "Chance de moedas extras no impacto.", "passive": { "type": "coin_on_hit", "chance": 0.18, "value": 4 }, "trail": "Patinhas", "impact": "Moedas" },
	{ "id": "kitty", "name": "Gatinho", "rarity": "common", "primary": "#ff99cc", "secondary": "#ffeeaa", "desc": "Aumenta chance crítica.", "passive": { "type": "crit_chance", "value": 4 }, "trail": "Arranhão", "impact": "Crítico" },
	{ "id": "piggy", "name": "Porquinho", "rarity": "common", "primary": "#ff86aa", "secondary": "#ffd1dc", "desc": "Aumenta moedas ganhas.", "passive": { "type": "coin_multiplier", "value": 0.12 }, "trail": "Moedas", "impact": "Cofrinho" },
	{ "id": "bunny", "name": "Coelho", "rarity": "common", "primary": "#ffffff", "secondary": "#a7f3ff", "desc": "Aumenta velocidade da bolinha.", "passive": { "type": "speed", "value": 0.08 }, "trail": "Saltos", "impact": "Estalo" },
	{ "id": "slime", "name": "Slime", "rarity": "common", "primary": "#3dff8f", "secondary": "#00995a", "desc": "Chance de ricochete sem perder velocidade.", "passive": { "type": "slime_bounce", "chance": 0.14, "value": 0.14 }, "trail": "Gosma", "impact": "Quicar" },
	{ "id": "ghost", "name": "Fantasma", "rarity": "common", "primary": "#dff7ff", "secondary": "#8a7cff", "desc": "Chance de atravessar parte sólida.", "passive": { "type": "phase_solid", "chance": 0.06, "value": 1 }, "trail": "Névoa", "impact": "Fase" },
	{ "id": "chick", "name": "Pintinho", "rarity": "common", "primary": "#ffe66d", "secondary": "#ffb703", "desc": "Moedas extras em quebras rápidas.", "passive": { "type": "coin_on_hit", "chance": 0.16, "value": 5 }, "trail": "Plumas", "impact": "Piu neon" },
	{ "id": "frog", "name": "Sapo", "rarity": "common", "primary": "#7cff6b", "secondary": "#0f8f45", "desc": "Pequeno bônus de ricochete.", "passive": { "type": "slime_bounce", "chance": 0.12, "value": 0.12 }, "trail": "Pulos", "impact": "Salto" },
	{ "id": "monkey", "name": "Macaquinho", "rarity": "common", "primary": "#c08457", "secondary": "#ffcf8a", "desc": "Bônus leve de XP.", "passive": { "type": "xp_multiplier", "value": 0.08 }, "trail": "Faíscas", "impact": "Combo" },
	{ "id": "penguin", "name": "Pinguim", "rarity": "common", "primary": "#111827", "secondary": "#dff7ff", "desc": "Pequena chance de desacelerar anéis.", "passive": { "type": "slow_ring", "chance": 0.1, "value": 0.75, "durationMs": 1500 }, "trail": "Gelo fino", "impact": "Escorregar" },
	{ "id": "hamster", "name": "Hamster", "rarity": "common", "primary": "#d8a45f", "secondary": "#fff0c2", "desc": "Moedas extras em impactos rápidos.", "passive": { "type": "coin_on_hit", "chance": 0.14, "value": 5 }, "trail": "Sementes neon", "impact": "Rodinha" },
	{ "id": "bear_common", "name": "Ursinho", "rarity": "common", "primary": "#9b5f2e", "secondary": "#ffd29a", "desc": "Um pouco mais de dano.", "passive": { "type": "damage_multiplier", "value": 0.06 }, "trail": "Pelúcia", "impact": "Patada" },
	{ "id": "panda", "name": "Panda", "rarity": "common", "primary": "#f8fafc", "secondary": "#111827", "desc": "Bônus leve de XP.", "passive": { "type": "xp_multiplier", "value": 0.07 }, "trail": "Bambu", "impact": "Pancada" },
	{ "id": "fox_common", "name": "Raposa", "rarity": "common", "primary": "#ff8a00", "secondary": "#fff3b0", "desc": "Velocidade levemente maior.", "passive": { "type": "speed", "value": 0.07 }, "trail": "Cauda", "impact": "Sprint" },
	{ "id": "tiger_common", "name": "Tigre", "rarity": "common", "primary": "#ffb000", "secondary": "#111111", "desc": "Pequeno bônus crítico.", "passive": { "type": "crit_chance", "value": 3 }, "trail": "Listras", "impact": "Garra" },
	{ "id": "cow_common", "name": "Vaquinha", "rarity": "common", "primary": "#ffffff", "secondary": "#64748b", "desc": "Mais moedas ao final.", "passive": { "type": "coin_multiplier", "value": 0.08 }, "trail": "Sininho", "impact": "Mugido" },
	{ "id": "octopus_common", "name": "Polvo", "rarity": "common", "primary": "#ff4fd8", "secondary": "#7c3aed", "desc": "Chance baixa de ricochete.", "passive": { "type": "slime_bounce", "chance": 0.1, "value": 0.12 }, "trail": "Tentáculos", "impact": "Tinta" },
	{ "id": "fish_common", "name": "Peixinho", "rarity": "common", "primary": "#60a5fa", "secondary": "#00f0ff", "desc": "Aumenta a velocidade.", "passive": { "type": "speed", "value": 0.06 }, "trail": "Bolhas", "impact": "Nado" },
	{ "id": "bee_common", "name": "Abelha", "rarity": "common", "primary": "#ffd700", "secondary": "#111827", "desc": "Crítico leve.", "passive": { "type": "crit_chance", "value": 3 }, "trail": "Ferrão neon", "impact": "Zumbido" },
	{ "id": "ladybug_common", "name": "Joaninha", "rarity": "common", "primary": "#ef4444", "secondary": "#111827", "desc": "Pequeno bônus de moedas.", "passive": { "type": "coin_multiplier", "value": 0.07 }, "trail": "Pontinhos", "impact": "Sorte" },
	{ "id": "robot", "name": "Robô", "rarity": "rare", "primary": "#94a3b8", "secondary": "#00f0ff", "desc": "Calcula ricochetes eficientes.", "passive": { "type": "slime_bounce", "chance": 0.15, "value": 0.16 }, "trail": "Circuito", "impact": "Pulso digital" },
	{ "id": "skull", "name": "Caveira", "rarity": "rare", "primary": "#f8fafc", "secondary": "#ff0055", "desc": "Chance de crítico pesado.", "passive": { "type": "mega_crit", "chance": 0.08, "value": 2.7 }, "trail": "Ossos neon", "impact": "Rachadura" },
	{ "id": "fire", "name": "Fogo", "rarity": "rare", "primary": "#ff6b00", "secondary": "#ffdd55", "desc": "Aplica dano contínuo.", "passive": { "type": "burn", "chance": 0.17, "value": 4, "durationMs": 2600 }, "trail": "Fagulhas", "impact": "Burn" },
	{ "id": "ice", "name": "Gelo", "rarity": "rare", "primary": "#b8f3ff", "secondary": "#3b82f6", "desc": "Congela ou desacelera anéis.", "passive": { "type": "freeze_ring", "chance": 0.16, "value": 0.4, "durationMs": 2200 }, "trail": "Cristais", "impact": "Gelo" },
	{ "id": "lightning", "name": "Raio", "rarity": "rare", "primary": "#faff00", "secondary": "#00e5ff", "desc": "Corrente elétrica atinge outro anel.", "passive": { "type": "chain_damage", "chance": 0.15, "value": 0.45 }, "trail": "Raios", "impact": "Corrente" },
	{ "id": "star_rare", "name": "Estrela", "rarity": "rare", "primary": "#fff7ad", "secondary": "#ff8a00", "desc": "Melhora perfect escapes.", "passive": { "type": "perfect_chance", "value": 0.018 }, "trail": "Estelar", "impact": "Brilho" },
	{ "id": "moon", "name": "Lua", "rarity": "rare", "primary": "#e5e7eb", "secondary": "#818cf8", "desc": "Bônus leve de dano.", "passive": { "type": "damage_multiplier", "value": 0.1 }, "trail": "Luar", "impact": "Meia-lua" },
	{ "id": "planet", "name": "Planeta", "rarity": "rare", "primary": "#34d399", "secondary": "#fbbf24", "desc": "Melhora moedas e perfects.", "passive": { "type": "perfect_chance", "value": 0.02 }, "trail": "Órbita", "impact": "Anel orbital" },
	{ "id": "crystal", "name": "Cristal", "rarity": "rare", "primary": "#67e8f9", "secondary": "#a855f7", "desc": "Bônus de gemas por perfect.", "passive": { "type": "perfect_chance", "value": 0.025 }, "trail": "Lapidação", "impact": "Cristal" },
	{ "id": "comet", "name": "Cometa", "rarity": "rare", "primary": "#ff8a00", "secondary": "#60a5fa", "desc": "Mais velocidade e impacto.", "passive": { "type": "speed", "value": 0.12 }, "trail": "Cauda", "impact": "Impacto" },
	{ "id": "wolf_rare", "name": "Lobo", "rarity": "rare", "primary": "#94a3b8", "secondary": "#38bdf8", "desc": "Dano e crítico estáveis.", "passive": { "type": "damage_multiplier", "value": 0.1 }, "trail": "Uivo", "impact": "Mordida" },
	{ "id": "dragonling_rare", "name": "Dragãozinho", "rarity": "rare", "primary": "#22c55e", "secondary": "#ff8a00", "desc": "Chance de queimar anéis.", "passive": { "type": "burn", "chance": 0.15, "value": 4, "durationMs": 2400 }, "trail": "Fumaça", "impact": "Sopro" },
	{ "id": "alien_rare", "name": "Alien", "rarity": "rare", "primary": "#a3ff12", "secondary": "#00f0ff", "desc": "Melhora perfect escapes.", "passive": { "type": "perfect_chance", "value": 0.02 }, "trail": "Órbita alien", "impact": "Abdução" },
	{ "id": "ninja_rare", "name": "Ninja", "rarity": "rare", "primary": "#111827", "secondary": "#7dd3fc", "desc": "Mais velocidade e crítico.", "passive": { "type": "speed", "value": 0.11 }, "trail": "Sombras", "impact": "Corte" },
	{ "id": "wizard_rare", "name": "Mago", "rarity": "rare", "primary": "#7c3aed", "secondary": "#fbbf24", "desc": "Chance de desacelerar anéis.", "passive": { "type": "slow_ring", "chance": 0.12, "value": 0.7, "durationMs": 1800 }, "trail": "Runas", "impact": "Feitiço" },
	{ "id": "satellite_rare", "name": "Satélite", "rarity": "rare", "primary": "#9ca3af", "secondary": "#22d3ee", "desc": "Corrente leve entre anéis.", "passive": { "type": "chain_damage", "chance": 0.11, "value": 0.32 }, "trail": "Sinal", "impact": "Laser orbital" },
	{ "id": "meteor_rare", "name": "Meteoro", "rarity": "rare", "primary": "#f97316", "secondary": "#7f1d1d", "desc": "Impacto mais forte.", "passive": { "type": "damage_multiplier", "value": 0.12 }, "trail": "Fogo espacial", "impact": "Cratera" },
	{ "id": "purple_crystal", "name": "Cristal Roxo", "rarity": "rare", "primary": "#a855f7", "secondary": "#22d3ee", "desc": "Aumenta chance de diamante em perfect.", "passive": { "type": "perfect_chance", "value": 0.026 }, "trail": "Cristais", "impact": "Oráculo" },
	{ "id": "neon_heart", "name": "Coração Neon", "rarity": "rare", "primary": "#38bdf8", "secondary": "#ec4899", "desc": "Mais XP ao final.", "passive": { "type": "xp_multiplier", "value": 0.12 }, "trail": "Batimentos", "impact": "Pulso" },
	{ "id": "bomb_rare", "name": "Bomba", "rarity": "rare", "primary": "#111827", "secondary": "#facc15", "desc": "Chance de dano em área.", "passive": { "type": "area_damage", "chance": 0.1, "value": 0.34 }, "trail": "Fumaça", "impact": "Explosão" },
	{ "id": "red_eye", "name": "Olho Carmesim", "rarity": "epic", "primary": "#ff183f", "secondary": "#111111", "desc": "Pode desacelerar o anel atingido.", "passive": { "type": "slow_ring", "chance": 0.2, "value": 0.52, "durationMs": 2600 }, "trail": "Foco carmesim", "impact": "Olhar lento" },
	{ "id": "cosmic_eye", "name": "Olho Cósmico", "rarity": "epic", "primary": "#7c3aed", "secondary": "#22d3ee", "desc": "Aumenta a chance de diamante por perfect.", "passive": { "type": "perfect_chance", "value": 0.04 }, "trail": "Galáxia", "impact": "Constelação" },
	{ "id": "tiny_dragon", "name": "Dragão Pequeno", "rarity": "epic", "primary": "#22c55e", "secondary": "#ff6b00", "desc": "Chamas extras no impacto.", "passive": { "type": "burn", "chance": 0.22, "value": 5, "durationMs": 3200 }, "trail": "Escamas neon", "impact": "Sopro flamejante" },
	{ "id": "shadow_orb", "name": "Esfera Sombria", "rarity": "epic", "primary": "#20113f", "secondary": "#8b5cf6", "desc": "Dano extra em impactos críticos.", "passive": { "type": "mega_crit", "chance": 0.13, "value": 3.2 }, "trail": "Sombra", "impact": "Vazio" },
	{ "id": "solar_orb", "name": "Esfera Solar", "rarity": "epic", "primary": "#fff176", "secondary": "#ff4d00", "desc": "Dano em área em explosões solares.", "passive": { "type": "area_damage", "chance": 0.16, "value": 0.48 }, "trail": "Solar", "impact": "Explosão" },
	{ "id": "electric_core", "name": "Núcleo Elétrico", "rarity": "epic", "primary": "#faff00", "secondary": "#00e5ff", "desc": "Corrente mais forte entre anéis.", "passive": { "type": "chain_damage", "chance": 0.22, "value": 0.6 }, "trail": "Bobina", "impact": "Descarga" },
	{ "id": "astral_eye", "name": "Olho Astral", "rarity": "epic", "primary": "#22d3ee", "secondary": "#7c3aed", "desc": "Perfects melhores e brilho astral.", "passive": { "type": "perfect_chance", "value": 0.04 }, "trail": "Olhar astral", "impact": "Foco" },
	{ "id": "living_plasma", "name": "Plasma Vivo", "rarity": "epic", "primary": "#ff4fd8", "secondary": "#00f0ff", "desc": "Dano em cadeia orgânico.", "passive": { "type": "chain_damage", "chance": 0.18, "value": 0.52 }, "trail": "Plasma", "impact": "Mutação" },
	{ "id": "radioactive_core", "name": "Núcleo Radioativo", "rarity": "epic", "primary": "#39ff14", "secondary": "#111827", "desc": "Queima e enfraquece anéis.", "passive": { "type": "burn", "chance": 0.2, "value": 5, "durationMs": 3300 }, "trail": "Radiação", "impact": "Contágio" },
	{ "id": "blue_comet", "name": "Cometa Azul", "rarity": "epic", "primary": "#60a5fa", "secondary": "#00f0ff", "desc": "Velocidade com dano superior.", "passive": { "type": "speed", "value": 0.16 }, "trail": "Cauda azul", "impact": "Impacto azul" },
	{ "id": "neon_spiral", "name": "Espiral Neon", "rarity": "epic", "primary": "#00f0ff", "secondary": "#ff4fd8", "desc": "Desacelera anéis em espiral.", "passive": { "type": "slow_ring", "chance": 0.18, "value": 0.58, "durationMs": 2400 }, "trail": "Espiral", "impact": "Turbilhão" },
	{ "id": "flaming_skull", "name": "Caveira Flamejante", "rarity": "epic", "primary": "#ff4500", "secondary": "#111827", "desc": "Críticos queimam.", "passive": { "type": "mega_crit", "chance": 0.12, "value": 3 }, "trail": "Chamas", "impact": "Riso flamejante" },
	{ "id": "orbital_blade", "name": "Lâmina Orbital", "rarity": "epic", "primary": "#c0f2ff", "secondary": "#7c3aed", "desc": "Cortes em cadeia.", "passive": { "type": "chain_damage", "chance": 0.19, "value": 0.5 }, "trail": "Lâminas", "impact": "Corte orbital" },
	{ "id": "neon_dragon", "name": "Dragão Neon", "rarity": "epic", "primary": "#00f0ff", "secondary": "#ff00aa", "desc": "Fogo neon em anéis resistentes.", "passive": { "type": "burn", "chance": 0.24, "value": 5, "durationMs": 3200 }, "trail": "Escamas neon", "impact": "Sopro neon" },
	{ "id": "ghost_mask", "name": "Máscara Fantasma", "rarity": "epic", "primary": "#dff7ff", "secondary": "#8b5cf6", "desc": "Pode atravessar sólidos.", "passive": { "type": "phase_solid", "chance": 0.09, "value": 1 }, "trail": "Máscara", "impact": "Assombro" },
	{ "id": "solar_guardian", "name": "Guardião Solar", "rarity": "epic", "primary": "#ffd700", "secondary": "#ff4500", "desc": "Dano em área solar.", "passive": { "type": "area_damage", "chance": 0.18, "value": 0.5 }, "trail": "Escudo solar", "impact": "Erupção" },
	{ "id": "ripple_eye", "name": "Olho Espiral Roxo", "rarity": "legendary", "primary": "#b88cff", "secondary": "#4c1d95", "desc": "Pode repelir anéis para fora.", "passive": { "type": "repel_ring", "chance": 0.2, "value": 20 }, "trail": "Ondas roxas", "impact": "Repulsão" },
	{ "id": "black_hole", "name": "Buraco Negro", "rarity": "legendary", "primary": "#0b0018", "secondary": "#a855f7", "desc": "Pode causar dano em área gravitacional.", "passive": { "type": "area_damage", "chance": 0.22, "value": 0.62 }, "trail": "Gravidade", "impact": "Singularidade" },
	{ "id": "neon_phoenix", "name": "Fênix Neon", "rarity": "legendary", "primary": "#ff4fd8", "secondary": "#ffb000", "desc": "Críticos queimam anéis próximos.", "passive": { "type": "burn", "chance": 0.28, "value": 7, "durationMs": 3600 }, "trail": "Plumas neon", "impact": "Renascimento" },
	{ "id": "astral_dragon", "name": "Dragão Astral", "rarity": "legendary", "primary": "#22d3ee", "secondary": "#7c3aed", "desc": "Dano e XP superiores.", "passive": { "type": "damage_multiplier", "value": 0.22 }, "trail": "Astral", "impact": "Sopro astral" },
	{ "id": "ghost_king", "name": "Rei Fantasma", "rarity": "legendary", "primary": "#dff7ff", "secondary": "#8a7cff", "desc": "Atravessa sólidos com mais frequência.", "passive": { "type": "phase_solid", "chance": 0.12, "value": 1 }, "trail": "Coroa espectral", "impact": "Fase real" },
	{ "id": "collapsed_star", "name": "Estrela Colapsada", "rarity": "legendary", "primary": "#ffd700", "secondary": "#7c2d12", "desc": "Área crítica devastadora.", "passive": { "type": "area_damage", "chance": 0.25, "value": 0.72 }, "trail": "Supernova", "impact": "Colapso" },
	{ "id": "black_sun", "name": "Sol Negro", "rarity": "legendary", "primary": "#050505", "secondary": "#ff4fd8", "desc": "Gravidade e dano em área.", "passive": { "type": "area_damage", "chance": 0.24, "value": 0.7 }, "trail": "Eclipse", "impact": "Corona negra" },
	{ "id": "cosmic_emperor", "name": "Imperador Cósmico", "rarity": "legendary", "primary": "#ffd700", "secondary": "#7c3aed", "desc": "Dano e moedas de elite.", "passive": { "type": "coin_multiplier", "value": 0.24 }, "trail": "Manto cósmico", "impact": "Decreto" },
	{ "id": "galactic_phoenix", "name": "Fênix Galáctica", "rarity": "legendary", "primary": "#ff4fd8", "secondary": "#ffd700", "desc": "Queima anéis próximos.", "passive": { "type": "burn", "chance": 0.3, "value": 7, "durationMs": 3800 }, "trail": "Plumas galácticas", "impact": "Renascimento" },
	{ "id": "void_dragon", "name": "Dragão do Vazio", "rarity": "legendary", "primary": "#111827", "secondary": "#8b5cf6", "desc": "Crítico cósmico poderoso.", "passive": { "type": "cosmic_critical", "chance": 0.18, "value": 0.28 }, "trail": "Vazio", "impact": "Sopro vazio" },
	{ "id": "star_king", "name": "Rei das Estrelas", "rarity": "legendary", "primary": "#fff7ad", "secondary": "#38bdf8", "desc": "Mais XP e perfects.", "passive": { "type": "xp_multiplier", "value": 0.22 }, "trail": "Constelação real", "impact": "Estrela guia" },
	{ "id": "plasma_heart", "name": "Coração de Plasma", "rarity": "legendary", "primary": "#ff4fd8", "secondary": "#00f0ff", "desc": "Pulsos de área.", "passive": { "type": "area_damage", "chance": 0.23, "value": 0.68 }, "trail": "Batimento plasma", "impact": "Pulso" },
	{ "id": "celestial_core", "name": "Núcleo Celestial", "rarity": "legendary", "primary": "#fef3c7", "secondary": "#22d3ee", "desc": "Dano e controle celeste.", "passive": { "type": "slow_ring", "chance": 0.22, "value": 0.48, "durationMs": 2800 }, "trail": "Aura celestial", "impact": "Julgamento" },
	{ "id": "ring_devourer", "name": "Devorador de Anéis", "rarity": "legendary", "primary": "#0f172a", "secondary": "#f97316", "desc": "Dano forte contra anéis externos.", "passive": { "type": "damage_multiplier", "value": 0.25 }, "trail": "Fome orbital", "impact": "Devorar" },
	{ "id": "dimensional_guardian", "name": "Guardião Dimensional", "rarity": "legendary", "primary": "#a855f7", "secondary": "#22d3ee", "desc": "Repulsa anéis perigosos.", "passive": { "type": "repel_ring", "chance": 0.21, "value": 24 }, "trail": "Dimensão", "impact": "Barreira" },
	{ "id": "astral_crown", "name": "Coroa Astral", "rarity": "legendary", "primary": "#ffd700", "secondary": "#a855f7", "desc": "Críticos e XP melhores.", "passive": { "type": "crit_chance", "value": 9 }, "trail": "Coroa astral", "impact": "Realeza" },
	{ "id": "infinite_pulse", "name": "Pulso Infinito", "rarity": "common", "primary": "#00ff88", "secondary": "#00f0ff", "desc": "Recompensa por sobreviver 1 minuto no Infinito. Melhora moedas.", "passive": { "type": "coin_multiplier", "value": 0.08 }, "trail": "Pulso infinito", "impact": "Eco" },
	{ "id": "blue_vortex", "name": "Vórtice Azul", "rarity": "common", "primary": "#38bdf8", "secondary": "#1d4ed8", "desc": "Recompensa por quebrar 25 anéis no Infinito. Melhora velocidade.", "passive": { "type": "speed", "value": 0.06 }, "trail": "Vórtice", "impact": "Giro" },
	{ "id": "loop_flame", "name": "Chama de Loop", "rarity": "rare", "primary": "#ff6b00", "secondary": "#ffd166", "desc": "Recompensa por sobreviver 3 minutos no Infinito. Queima anéis.", "passive": { "type": "burn", "chance": 0.14, "value": 4, "durationMs": 2400 }, "trail": "Chama circular", "impact": "Loop ardente" },
	{ "id": "red_comet", "name": "Cometa Rubro", "rarity": "rare", "primary": "#ef4444", "secondary": "#f97316", "desc": "Recompensa por quebrar 50 anéis no Infinito. Aumenta dano.", "passive": { "type": "damage_multiplier", "value": 0.11 }, "trail": "Cauda rubra", "impact": "Impacto rubro" },
	{ "id": "neon_eclipse", "name": "Eclipse Neon", "rarity": "epic", "primary": "#7c3aed", "secondary": "#00f0ff", "desc": "Recompensa por sobreviver 5 minutos no Infinito. Melhora perfects.", "passive": { "type": "perfect_chance", "value": 0.04 }, "trail": "Eclipse", "impact": "Sombra neon" },
	{ "id": "endless_prism", "name": "Prisma Sem Fim", "rarity": "epic", "primary": "#22d3ee", "secondary": "#ff4fd8", "desc": "Recompensa por quebrar 100 anéis no Infinito. Aumenta XP.", "passive": { "type": "xp_multiplier", "value": 0.18 }, "trail": "Prisma", "impact": "Refração" },
	{ "id": "cosmic_fragment", "name": "Fragmento Cósmico", "rarity": "legendary", "primary": "#a855f7", "secondary": "#facc15", "desc": "Recompensa por sobreviver 10 minutos no Infinito. Aumenta dano.", "passive": { "type": "damage_multiplier", "value": 0.23 }, "trail": "Fragmentos", "impact": "Ruptura cósmica" },
	{ "id": "eternal_core", "name": "Núcleo Eterno", "rarity": "legendary", "primary": "#00f0ff", "secondary": "#ffd700", "desc": "Recompensa por completar 5 desafios no Infinito. Melhora moedas.", "passive": { "type": "coin_multiplier", "value": 0.24 }, "trail": "Núcleo eterno", "impact": "Pulso eterno" },
	{ "id": "infinite_vortex_mythic", "name": "Vórtice Infinito", "rarity": "mythic", "primary": "#ff4fd8", "secondary": "#00f0ff", "desc": "Recompensa por sobreviver 15 minutos no Infinito. Dano e XP elevados.", "passive": { "type": "cosmic_critical", "chance": 0.16, "value": 0.28 }, "trail": "Espiral mítica", "impact": "Colapso" },
	{ "id": "chrono_loop_mythic", "name": "Loop Cronal", "rarity": "mythic", "primary": "#f59e0b", "secondary": "#8b5cf6", "desc": "Recompensa por completar 10 desafios no Infinito. Controla anéis.", "passive": { "type": "slow_ring", "chance": 0.23, "value": 0.46, "durationMs": 3000 }, "trail": "Tempo quebrado", "impact": "Crono pulso" },
	{ "id": "omega_infinity", "name": "Ômega Infinito", "rarity": "ultimate", "primary": "#ffffff", "secondary": "#00ff88", "desc": "Recompensa por sobreviver 20 minutos no Infinito. Bônus completo.", "passive": { "type": "cosmic_critical", "chance": 0.24, "value": 0.38 }, "trail": "Ômega", "impact": "Ressonância final" },
	{ "id": "singularity_crown", "name": "Coroa da Singularidade", "rarity": "ultimate", "primary": "#020617", "secondary": "#ffd700", "desc": "Recompensa por quebrar 300 anéis no Infinito. Área extrema.", "passive": { "type": "area_damage", "chance": 0.32, "value": 0.98 }, "trail": "Coroa singular", "impact": "Gravidade real" },
	{ "id": "living_singularity", "name": "Singularidade Viva", "rarity": "ultimate", "primary": "#050015", "secondary": "#ff4fd8", "desc": "Ultimate raríssima com dano gravitacional extremo.", "passive": { "type": "area_damage", "chance": 0.32, "value": 0.95 }, "trail": "Horizonte vivo", "impact": "Gravidade total" },
	{ "id": "divine_core", "name": "Núcleo Divino", "rarity": "ultimate", "primary": "#fff7ad", "secondary": "#22d3ee", "desc": "Ultimate com bônus de dano, XP e controle.", "passive": { "type": "cosmic_critical", "chance": 0.22, "value": 0.34 }, "trail": "Aura divina", "impact": "Julgamento" },
	{ "id": "void_devourer_ultimate", "name": "Devorador do Vazio", "rarity": "ultimate", "primary": "#020617", "secondary": "#8b5cf6", "desc": "Ultimate oculta que devora anéis com ondas gravitacionais.", "passive": { "type": "area_damage", "chance": 0.34, "value": 1.02 }, "trail": "Abismo", "impact": "Devorar vazio" },
	{ "id": "cosmic_champion", "name": "Campeão Cósmico", "rarity": "ultimate", "primary": "#ffd700", "secondary": "#7c3aed", "desc": "Exclusiva por concluir os 50 estágios. Aumenta dano, moedas, XP, diamantes e pode repelir anéis em crítico.", "passive": { "type": "cosmic_critical", "chance": 0.28, "value": 0.4 }, "trail": "Aura cósmica dourada", "impact": "Repulsão crítica" },
	{ "id": "initial_neon_champion", "name": "Campeão Neon Inicial", "rarity": "ultimate", "primary": "#ffd700", "secondary": "#00aaff", "desc": "Ultimate exclusiva da primeira coroa na Liga Neon Bronze. Amplifica moedas, XP, combo e proteção.", "passive": { "type": "league_starter_champion", "chance": 0.08, "value": 0.24 }, "trail": "Trilha de campeão", "impact": "Escudo de ranking" },
	{ "id": "league_bronze_champion", "name": "Coroa Bronze Neon", "rarity": "legendary", "primary": "#cd7f32", "secondary": "#00f0ff", "desc": "Skin exclusiva por terminar em primeiro na divisão Bronze da Liga Neon.", "passive": { "type": "coin_multiplier", "value": 0.18 }, "trail": "Bronze neon", "impact": "Coroa inicial" },
	{ "id": "league_king_neon", "name": "Rei da Liga Neon", "rarity": "ultimate", "primary": "#ffd700", "secondary": "#8b5cf6", "desc": "Ultimate máxima de ranking. Aumenta dano, moedas, XP, perfect diamonds e libera onda em combo alto.", "passive": { "type": "league_king_wave", "chance": 0.18, "value": 0.38 }, "trail": "Coroas estelares", "impact": "Onda real" },
]

const GENERATED_SKINS := [
	{ "id": "aqua_bubble", "name": "Bolha Aqua", "name_pt": "Bolha Aqua", "name_en": "Aqua Bubble", "rarity": "common", "primary": "#36d7ff", "secondary": "#92f7ff", "desc": "Uma bolha neon azul que desliza melhor pelos aneis.", "desc_pt": "Uma bolha neon azul que desliza melhor pelos aneis.", "desc_en": "A translucent aqua neon bubble that glides better through rings.", "passive": { "type": "speed", "value": 0.045 }, "effects": ["speed"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Bau comum, roleta comum", "unlock_hint_pt": "Bau comum, roleta comum", "sources": ["common_chest", "common_wheel"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/aqua_bubble.png", "drop_pool": "common", "chest_chance": 0.09, "wheel": "common" },
	{ "id": "moon_pebble", "name": "Pedra Lunar", "name_pt": "Pedra Lunar", "name_en": "Moon Pebble", "rarity": "common", "primary": "#9fb7d5", "secondary": "#f8fafc", "desc": "Pequeno fragmento lunar que aumenta XP de forma simples.", "desc_pt": "Pequeno fragmento lunar que aumenta XP de forma simples.", "desc_en": "A small moon shard with a simple XP bonus.", "passive": { "type": "xp_multiplier", "value": 0.055 }, "effects": ["xp_multiplier"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Bau comum, missao diaria", "unlock_hint_pt": "Bau comum, missao diaria", "sources": ["common_chest", "daily_mission"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/moon_pebble.png", "drop_pool": "common", "chest_chance": 0.08, "wheel": "common" },
	{ "id": "neon_seed", "name": "Semente Neon", "name_pt": "Semente Neon", "name_en": "Neon Seed", "rarity": "common", "primary": "#45ff85", "secondary": "#0f8f45", "desc": "Uma semente viva que pode gerar moedas extras no impacto.", "desc_pt": "Uma semente viva que pode gerar moedas extras no impacto.", "desc_en": "A living neon seed that can create extra coins on impact.", "passive": { "type": "coin_on_hit", "chance": 0.13, "value": 4 }, "effects": ["coin_on_hit"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Bau comum", "unlock_hint_pt": "Bau comum", "sources": ["common_chest"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/neon_seed.png", "drop_pool": "common", "chest_chance": 0.08, "wheel": "common" },
	{ "id": "mini_ruby_orb", "name": "Mini Orbe Rubi", "name_pt": "Mini Orbe Rubi", "name_en": "Mini Ruby Orb", "rarity": "common", "primary": "#ff335f", "secondary": "#ff9abd", "desc": "Pequeno rubi energetico com chance critica basica.", "desc_pt": "Pequeno rubi energetico com chance critica basica.", "desc_en": "A small energetic ruby with basic critical chance.", "passive": { "type": "crit_chance", "value": 2.5 }, "effects": ["crit_chance"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Bau comum, conquista inicial", "unlock_hint_pt": "Bau comum, conquista inicial", "sources": ["common_chest", "starter_achievement"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/mini_ruby_orb.png", "drop_pool": "common", "chest_chance": 0.07, "wheel": "common" },
	{ "id": "cloud_orb", "name": "Orbe de Nuvem", "name_pt": "Orbe de Nuvem", "name_en": "Cloud Orb", "rarity": "common", "primary": "#e7fbff", "secondary": "#8bd9ff", "desc": "Esfera macia que ricocheteia com suavidade.", "desc_pt": "Esfera macia que ricocheteia com suavidade.", "desc_en": "A soft orb that bounces smoothly.", "passive": { "type": "slime_bounce", "chance": 0.1, "value": 0.1 }, "effects": ["slime_bounce"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Bau comum", "unlock_hint_pt": "Bau comum", "sources": ["common_chest"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/cloud_orb.png", "drop_pool": "common", "chest_chance": 0.07, "wheel": "common" },
	{ "id": "green_spark", "name": "Faisca Verde", "name_pt": "Faisca Verde", "name_en": "Green Spark", "rarity": "common", "primary": "#9dff26", "secondary": "#00ff88", "desc": "Pequena faisca que deixa o movimento mais agil.", "desc_pt": "Pequena faisca que deixa o movimento mais agil.", "desc_en": "A tiny green spark that makes movement more agile.", "passive": { "type": "speed", "value": 0.052 }, "effects": ["speed"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Bau comum, roleta", "unlock_hint_pt": "Bau comum, roleta", "sources": ["common_chest", "common_wheel"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/green_spark.png", "drop_pool": "common", "chest_chance": 0.08, "wheel": "common" },
	{ "id": "small_sunstone", "name": "Pedra Solar Pequena", "name_pt": "Pedra Solar Pequena", "name_en": "Small Sunstone", "rarity": "common", "primary": "#ffb000", "secondary": "#ff6b00", "desc": "Pedra quente com leve bonus de dano.", "desc_pt": "Pedra quente com leve bonus de dano.", "desc_en": "A warm stone with a light damage bonus.", "passive": { "type": "damage_multiplier", "value": 0.055 }, "effects": ["damage_multiplier"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Bau comum", "unlock_hint_pt": "Bau comum", "sources": ["common_chest"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/small_sunstone.png", "drop_pool": "common", "chest_chance": 0.07, "wheel": "common" },
	{ "id": "prism_drop", "name": "Gota Prismatica", "name_pt": "Gota Prismatica", "name_en": "Prism Drop", "rarity": "rare", "primary": "#8ffcff", "secondary": "#ff67d8", "desc": "Uma gota colorida que melhora escapes perfeitos.", "desc_pt": "Uma gota colorida que melhora escapes perfeitos.", "desc_en": "A colorful drop that improves perfect escapes.", "passive": { "type": "perfect_chance", "value": 0.018 }, "effects": ["perfect_chance"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Bau raro, roleta semanal", "unlock_hint_pt": "Bau raro, roleta semanal", "sources": ["rare_chest", "weekly_wheel"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/prism_drop.png", "drop_pool": "rare", "chest_chance": 0.06, "wheel": "weekly" },
	{ "id": "magnetic_core", "name": "Nucleo Magnetico", "name_pt": "Nucleo Magnetico", "name_en": "Magnetic Core", "rarity": "rare", "primary": "#233044", "secondary": "#ff4d6d", "desc": "Pode repelir levemente aneis perigosos.", "desc_pt": "Pode repelir levemente aneis perigosos.", "desc_en": "Can lightly repel dangerous rings.", "passive": { "type": "repel_ring", "chance": 0.11, "value": 12 }, "effects": ["repel_ring"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Bau raro", "unlock_hint_pt": "Bau raro", "sources": ["rare_chest"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/magnetic_core.png", "drop_pool": "rare", "chest_chance": 0.05, "wheel": "weekly" },
	{ "id": "tide_crystal", "name": "Cristal de Mare", "name_pt": "Cristal de Mare", "name_en": "Tide Crystal", "rarity": "rare", "primary": "#0b4a8f", "secondary": "#55d8ff", "desc": "Desacelera aneis com energia de mare.", "desc_pt": "Desacelera aneis com energia de mare.", "desc_en": "Slows rings with tidal energy.", "passive": { "type": "slow_ring", "chance": 0.13, "value": 0.66, "durationMs": 1900 }, "effects": ["slow_ring"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Bau raro, missao semanal", "unlock_hint_pt": "Bau raro, missao semanal", "sources": ["rare_chest", "weekly_mission"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/tide_crystal.png", "drop_pool": "rare", "chest_chance": 0.05, "wheel": "weekly" },
	{ "id": "golden_spark", "name": "Faisca Dourada", "name_pt": "Faisca Dourada", "name_en": "Golden Spark", "rarity": "rare", "primary": "#ffd700", "secondary": "#fff1a8", "desc": "Aumenta moedas recebidas.", "desc_pt": "Aumenta moedas recebidas.", "desc_en": "Increases coin gains.", "passive": { "type": "coin_multiplier", "value": 0.13 }, "effects": ["coin_multiplier"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Bau raro, roleta", "unlock_hint_pt": "Bau raro, roleta", "sources": ["rare_chest", "weekly_wheel"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/golden_spark.png", "drop_pool": "rare", "chest_chance": 0.06, "wheel": "weekly" },
	{ "id": "sapphire_eye", "name": "Olho de Safira", "name_pt": "Olho de Safira", "name_en": "Sapphire Eye", "rarity": "rare", "primary": "#2677ff", "secondary": "#9bd7ff", "desc": "Um olho azul que calcula impactos criticos.", "desc_pt": "Um olho azul que calcula impactos criticos.", "desc_en": "A sapphire eye that calculates critical impacts.", "passive": { "type": "crit_chance", "value": 4.5 }, "effects": ["crit_chance"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Bau raro", "unlock_hint_pt": "Bau raro", "sources": ["rare_chest"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/sapphire_eye.png", "drop_pool": "rare", "chest_chance": 0.05, "wheel": "weekly" },
	{ "id": "electric_sprout", "name": "Broto Eletrico", "name_pt": "Broto Eletrico", "name_en": "Electric Sprout", "rarity": "rare", "primary": "#4dff9a", "secondary": "#00d9ff", "desc": "Corrente eletrica leve entre aneis.", "desc_pt": "Corrente eletrica leve entre aneis.", "desc_en": "Light electric chains between rings.", "passive": { "type": "chain_damage", "chance": 0.12, "value": 0.34 }, "effects": ["chain_damage"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Bau raro, roleta semanal", "unlock_hint_pt": "Bau raro, roleta semanal", "sources": ["rare_chest", "weekly_wheel"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/electric_sprout.png", "drop_pool": "rare", "chest_chance": 0.05, "wheel": "weekly" },
	{ "id": "swift_mask", "name": "Mascara Veloz", "name_pt": "Mascara Veloz", "name_en": "Swift Mask", "rarity": "rare", "primary": "#111827", "secondary": "#18cfff", "desc": "Aumenta velocidade e resposta da bolinha.", "desc_pt": "Aumenta velocidade e resposta da bolinha.", "desc_en": "Increases speed and ball response.", "passive": { "type": "speed", "value": 0.12 }, "effects": ["speed"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Bau raro", "unlock_hint_pt": "Bau raro", "sources": ["rare_chest"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/swift_mask.png", "drop_pool": "rare", "chest_chance": 0.05, "wheel": "weekly" },
	{ "id": "blue_flame", "name": "Chama Azul", "name_pt": "Chama Azul", "name_en": "Blue Flame", "rarity": "rare", "primary": "#1ca7ff", "secondary": "#a8ecff", "desc": "Queima aneis com fogo azul.", "desc_pt": "Queima aneis com fogo azul.", "desc_en": "Burns rings with blue fire.", "passive": { "type": "burn", "chance": 0.16, "value": 4, "durationMs": 2600 }, "effects": ["burn"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Bau raro, missao", "unlock_hint_pt": "Bau raro, missao", "sources": ["rare_chest", "mission"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/blue_flame.png", "drop_pool": "rare", "chest_chance": 0.05, "wheel": "weekly" },
	{ "id": "storm_orb", "name": "Orbe Tempestade", "name_pt": "Orbe Tempestade", "name_en": "Storm Orb", "rarity": "epic", "primary": "#35e8ff", "secondary": "#7c3aed", "desc": "Descargas eletricas atingem aneis proximos.", "desc_pt": "Descargas eletricas atingem aneis proximos.", "desc_en": "Electric discharges hit nearby rings.", "passive": { "type": "chain_damage", "chance": 0.2, "value": 0.56 }, "effects": ["chain_damage"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Bau epico, roleta semanal", "unlock_hint_pt": "Bau epico, roleta semanal", "sources": ["epic_chest", "weekly_wheel"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/storm_orb.png", "drop_pool": "epic", "chest_chance": 0.04, "wheel": "weekly" },
	{ "id": "frost_guardian", "name": "Guardiao de Gelo", "name_pt": "Guardiao de Gelo", "name_en": "Frost Guardian", "rarity": "epic", "primary": "#a8f5ff", "secondary": "#2f80ff", "desc": "Congela aneis por curto tempo.", "desc_pt": "Congela aneis por curto tempo.", "desc_en": "Freezes rings for a short time.", "passive": { "type": "freeze_ring", "chance": 0.19, "value": 0.44, "durationMs": 2600 }, "effects": ["freeze_ring"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Bau epico, conquista de perfects", "unlock_hint_pt": "Bau epico, conquista de perfects", "sources": ["epic_chest", "perfect_achievement"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/frost_guardian.png", "drop_pool": "epic", "chest_chance": 0.035, "wheel": "weekly" },
	{ "id": "flaming_heart", "name": "Coracao Flamejante", "name_pt": "Coracao Flamejante", "name_en": "Flaming Heart", "rarity": "epic", "primary": "#ff365e", "secondary": "#ff8a00", "desc": "Queima aneis e pode gerar moedas no impacto.", "desc_pt": "Queima aneis e pode gerar moedas no impacto.", "desc_en": "Burns rings and can generate coins on impact.", "passive": { "type": "burn", "chance": 0.2, "value": 5, "durationMs": 3200 }, "effects": ["burn"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Bau epico", "unlock_hint_pt": "Bau epico", "sources": ["epic_chest"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/flaming_heart.png", "drop_pool": "epic", "chest_chance": 0.035, "wheel": "weekly" },
	{ "id": "green_neon_eye", "name": "Olho de Neon Verde", "name_pt": "Olho de Neon Verde", "name_en": "Green Neon Eye", "rarity": "epic", "primary": "#39ff14", "secondary": "#00f0ff", "desc": "Foca no anel e reduz sua velocidade.", "desc_pt": "Foca no anel e reduz sua velocidade.", "desc_en": "Focuses a ring and reduces its speed.", "passive": { "type": "slow_ring", "chance": 0.18, "value": 0.54, "durationMs": 2500 }, "effects": ["slow_ring"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Bau epico, missao semanal", "unlock_hint_pt": "Bau epico, missao semanal", "sources": ["epic_chest", "weekly_mission"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/green_neon_eye.png", "drop_pool": "epic", "chest_chance": 0.035, "wheel": "weekly" },
	{ "id": "electric_prism", "name": "Prisma Eletrico", "name_pt": "Prisma Eletrico", "name_en": "Electric Prism", "rarity": "epic", "primary": "#ffe84d", "secondary": "#00e5ff", "desc": "Encadeia dano com descargas prismaticas.", "desc_pt": "Encadeia dano com descargas prismaticas.", "desc_en": "Chains damage with prismatic discharges.", "passive": { "type": "chain_damage", "chance": 0.19, "value": 0.55 }, "effects": ["chain_damage"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Bau epico, roleta", "unlock_hint_pt": "Bau epico, roleta", "sources": ["epic_chest", "weekly_wheel"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/electric_prism.png", "drop_pool": "epic", "chest_chance": 0.035, "wheel": "weekly" },
	{ "id": "pink_comet", "name": "Cometa Rosa", "name_pt": "Cometa Rosa", "name_en": "Pink Comet", "rarity": "epic", "primary": "#ff69d8", "secondary": "#64e8ff", "desc": "Velocidade alta com bonus de XP.", "desc_pt": "Velocidade alta com bonus de XP.", "desc_en": "High speed with XP bonus.", "passive": { "type": "speed", "value": 0.15 }, "effects": ["speed"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Modo infinito, bau epico", "unlock_hint_pt": "Modo infinito, bau epico", "sources": ["infinite_mode", "epic_chest"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/pink_comet.png", "drop_pool": "epic", "chest_chance": 0.035, "wheel": "weekly" },
	{ "id": "astral_mirror", "name": "Espelho Astral", "name_pt": "Espelho Astral", "name_en": "Astral Mirror", "rarity": "epic", "primary": "#c9b6ff", "secondary": "#57e7ff", "desc": "Chance de atravessar parte solida.", "desc_pt": "Chance de atravessar parte solida.", "desc_en": "Chance to phase through solid ring parts.", "passive": { "type": "phase_solid", "chance": 0.09, "value": 1 }, "effects": ["phase_solid"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Conquista de fases", "unlock_hint_pt": "Conquista de fases", "sources": ["phase_achievement"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/astral_mirror.png", "drop_pool": "epic", "chest_chance": 0.035, "wheel": "weekly" },
	{ "id": "ruby_dragon", "name": "Dragao Rubro", "name_pt": "Dragao Rubro", "name_en": "Ruby Dragon", "rarity": "legendary", "primary": "#db1744", "secondary": "#ff8a00", "desc": "Criticos aplicam chamas fortes.", "desc_pt": "Criticos aplicam chamas fortes.", "desc_en": "Critical hits apply strong flames.", "passive": { "type": "mega_crit", "chance": 0.15, "value": 3.1 }, "effects": ["mega_crit"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Bau lendario, conquista de dano", "unlock_hint_pt": "Bau lendario, conquista de dano", "sources": ["legendary_chest", "damage_achievement"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/ruby_dragon.png", "drop_pool": "legendary", "chest_chance": 0.025, "wheel": "monthly" },
	{ "id": "aurora_core", "name": "Nucleo da Aurora", "name_pt": "Nucleo da Aurora", "name_en": "Aurora Core", "rarity": "legendary", "primary": "#22ffb5", "secondary": "#7c3aed", "desc": "Aumenta XP e melhora escapes perfeitos.", "desc_pt": "Aumenta XP e melhora escapes perfeitos.", "desc_en": "Increases XP and improves perfect escapes.", "passive": { "type": "xp_multiplier", "value": 0.24 }, "effects": ["xp_multiplier"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Bau lendario, roleta mensal", "unlock_hint_pt": "Bau lendario, roleta mensal", "sources": ["legendary_chest", "monthly_wheel"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/aurora_core.png", "drop_pool": "legendary", "chest_chance": 0.025, "wheel": "monthly" },
	{ "id": "obsidian_sentinel", "name": "Sentinela de Obsidiana", "name_pt": "Sentinela de Obsidiana", "name_en": "Obsidian Sentinel", "rarity": "legendary", "primary": "#08080c", "secondary": "#ff7a1a", "desc": "Dano alto e repulsao ocasional.", "desc_pt": "Dano alto e repulsao ocasional.", "desc_en": "High damage and occasional repulsion.", "passive": { "type": "damage_multiplier", "value": 0.24 }, "effects": ["damage_multiplier"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Bau lendario, Liga Neon", "unlock_hint_pt": "Bau lendario, Liga Neon", "sources": ["legendary_chest", "neon_league"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/obsidian_sentinel.png", "drop_pool": "legendary", "chest_chance": 0.02, "wheel": "monthly" },
	{ "id": "plasma_crown", "name": "Coroa de Plasma", "name_pt": "Coroa de Plasma", "name_en": "Plasma Crown", "rarity": "legendary", "primary": "#b800ff", "secondary": "#00f0ff", "desc": "Pulsos de plasma atingem aneis proximos.", "desc_pt": "Pulsos de plasma atingem aneis proximos.", "desc_en": "Plasma pulses hit nearby rings.", "passive": { "type": "area_damage", "chance": 0.22, "value": 0.7 }, "effects": ["area_damage"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Bau lendario", "unlock_hint_pt": "Bau lendario", "sources": ["legendary_chest"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/plasma_crown.png", "drop_pool": "legendary", "chest_chance": 0.02, "wheel": "monthly" },
	{ "id": "cosmic_serpent", "name": "Serpente Cosmica", "name_pt": "Serpente Cosmica", "name_en": "Cosmic Serpent", "rarity": "legendary", "primary": "#10162f", "secondary": "#47f6ff", "desc": "Energia serpenteia entre aneis e desacelera alvos.", "desc_pt": "Energia serpenteia entre aneis e desacelera alvos.", "desc_en": "Energy snakes between rings and slows targets.", "passive": { "type": "chain_damage", "chance": 0.21, "value": 0.62 }, "effects": ["chain_damage"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Conquista de combo", "unlock_hint_pt": "Conquista de combo", "sources": ["combo_achievement"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/cosmic_serpent.png", "drop_pool": "legendary", "chest_chance": 0.02, "wheel": "monthly" },
	{ "id": "golden_eclipse", "name": "Eclipse Dourado", "name_pt": "Eclipse Dourado", "name_en": "Golden Eclipse", "rarity": "legendary", "primary": "#ffd700", "secondary": "#08080c", "desc": "Bonus de moedas e critico cosmico.", "desc_pt": "Bonus de moedas e critico cosmico.", "desc_en": "Coin bonus and cosmic criticals.", "passive": { "type": "coin_multiplier", "value": 0.25 }, "effects": ["coin_multiplier"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Roleta mensal, bau lendario", "unlock_hint_pt": "Roleta mensal, bau lendario", "sources": ["monthly_wheel", "legendary_chest"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/golden_eclipse.png", "drop_pool": "legendary", "chest_chance": 0.02, "wheel": "monthly" },
	{ "id": "chronal_orb", "name": "Orbe Cronal", "name_pt": "Orbe Cronal", "name_en": "Chronal Orb", "rarity": "mythic", "primary": "#f2b84b", "secondary": "#8b5cf6", "desc": "Manipula o tempo dos aneis e permite controle direcional moderado.", "desc_pt": "Manipula o tempo dos aneis e permite controle direcional moderado.", "desc_en": "Manipulates ring time and enables moderate directional control.", "passive": { "type": "slow_ring", "chance": 0.24, "value": 0.42, "durationMs": 3100 }, "effects": ["slow_ring", "control"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Infinito 8 min, bau lendario raro", "unlock_hint_pt": "Infinito 8 min, bau lendario raro", "sources": ["infinite_8m", "legendary_chest_rare"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/chronal_orb.png", "drop_pool": "mythic", "chest_chance": 0.008, "wheel": "monthly" },
	{ "id": "quantum_heart", "name": "Coracao Quantico", "name_pt": "Coracao Quantico", "name_en": "Quantum Heart", "rarity": "mythic", "primary": "#ff4fd8", "secondary": "#00f0ff", "desc": "Alterna entre dimensoes e aumenta XP.", "desc_pt": "Alterna entre dimensoes e aumenta XP.", "desc_en": "Shifts between dimensions and increases XP.", "passive": { "type": "phase_solid", "chance": 0.13, "value": 1 }, "effects": ["phase_solid"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Conquista de fases avancadas", "unlock_hint_pt": "Conquista de fases avancadas", "sources": ["advanced_phase_achievement"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/quantum_heart.png", "drop_pool": "mythic", "chest_chance": 0.007, "wheel": "monthly" },
	{ "id": "abyss_core", "name": "Nucleo Abissal", "name_pt": "Nucleo Abissal", "name_en": "Abyss Core", "rarity": "mythic", "primary": "#070014", "secondary": "#7c3aed", "desc": "Cria pulso abissal que afeta aneis proximos.", "desc_pt": "Cria pulso abissal que afeta aneis proximos.", "desc_en": "Creates an abyssal pulse that affects nearby rings.", "passive": { "type": "area_damage", "chance": 0.25, "value": 0.82 }, "effects": ["area_damage"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Bau lendario, Liga Neon", "unlock_hint_pt": "Bau lendario, Liga Neon", "sources": ["legendary_chest", "neon_league"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/abyss_core.png", "drop_pool": "mythic", "chest_chance": 0.007, "wheel": "monthly" },
	{ "id": "boreal_phoenix", "name": "Fenix Boreal", "name_pt": "Fenix Boreal", "name_en": "Boreal Phoenix", "rarity": "mythic", "primary": "#42e8ff", "secondary": "#ff8a00", "desc": "Mistura fogo e gelo em impactos especiais.", "desc_pt": "Mistura fogo e gelo em impactos especiais.", "desc_en": "Mixes fire and ice in special impacts.", "passive": { "type": "burn", "chance": 0.27, "value": 7, "durationMs": 3600 }, "effects": ["burn"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Roleta mensal", "unlock_hint_pt": "Roleta mensal", "sources": ["monthly_wheel"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/boreal_phoenix.png", "drop_pool": "mythic", "chest_chance": 0.006, "wheel": "monthly" },
	{ "id": "temporal_blade", "name": "Lamina Temporal", "name_pt": "Lamina Temporal", "name_en": "Temporal Blade", "rarity": "mythic", "primary": "#d9e4ff", "secondary": "#7c3aed", "desc": "Cortes temporais encadeiam dano.", "desc_pt": "Cortes temporais encadeiam dano.", "desc_en": "Temporal cuts chain damage.", "passive": { "type": "chain_damage", "chance": 0.24, "value": 0.74 }, "effects": ["chain_damage"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Missao mensal", "unlock_hint_pt": "Missao mensal", "sources": ["monthly_mission"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/temporal_blade.png", "drop_pool": "mythic", "chest_chance": 0.006, "wheel": "monthly" },
	{ "id": "split_prism", "name": "Prisma Dividido", "name_pt": "Prisma Dividido", "name_en": "Split Prism", "rarity": "mythic", "primary": "#00f0ff", "secondary": "#ff4fd8", "desc": "Perfects geram bonus raros.", "desc_pt": "Perfects geram bonus raros.", "desc_en": "Perfects generate rare bonuses.", "passive": { "type": "perfect_chance", "value": 0.065 }, "effects": ["perfect_chance"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Bau lendario raro", "unlock_hint_pt": "Bau lendario raro", "sources": ["legendary_chest_rare"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/split_prism.png", "drop_pool": "mythic", "chest_chance": 0.006, "wheel": "monthly" },
	{ "id": "void_eye", "name": "Olho do Vacuo", "name_pt": "Olho do Vacuo", "name_en": "Void Eye", "rarity": "mythic", "primary": "#050011", "secondary": "#a855f7", "desc": "Criticos geram pulso do vazio.", "desc_pt": "Criticos geram pulso do vazio.", "desc_en": "Criticals create a void pulse.", "passive": { "type": "cosmic_critical", "chance": 0.2, "value": 0.34 }, "effects": ["cosmic_critical"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Liga Neon alta", "unlock_hint_pt": "Liga Neon alta", "sources": ["high_neon_league"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/void_eye.png", "drop_pool": "mythic", "chest_chance": 0.006, "wheel": "monthly" },
	{ "id": "living_star", "name": "Estrela Viva", "name_pt": "Estrela Viva", "name_en": "Living Star", "rarity": "mythic", "primary": "#fff7ad", "secondary": "#ff6b00", "desc": "Explosoes solares controladas atingem aneis.", "desc_pt": "Explosoes solares controladas atingem aneis.", "desc_en": "Controlled solar bursts hit rings.", "passive": { "type": "area_damage", "chance": 0.27, "value": 0.86 }, "effects": ["area_damage"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Infinito 12 min", "unlock_hint_pt": "Infinito 12 min", "sources": ["infinite_12m"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/living_star.png", "drop_pool": "mythic", "chest_chance": 0.006, "wheel": "monthly" },
	{ "id": "ether_guardian", "name": "Guardiao de Eter", "name_pt": "Guardiao de Eter", "name_en": "Ether Guardian", "rarity": "mythic", "primary": "#5ee7ff", "secondary": "#8b5cf6", "desc": "Protege a trajetoria e permite controle direcional.", "desc_pt": "Protege a trajetoria e permite controle direcional.", "desc_en": "Protects trajectory and enables directional control.", "passive": { "type": "repel_ring", "chance": 0.23, "value": 26 }, "effects": ["repel_ring", "control"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Conquista de Liga Neon", "unlock_hint_pt": "Conquista de Liga Neon", "sources": ["league_achievement"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/ether_guardian.png", "drop_pool": "mythic", "chest_chance": 0.006, "wheel": "monthly" },
	{ "id": "plasma_dragon", "name": "Dragao de Plasma", "name_pt": "Dragao de Plasma", "name_en": "Plasma Dragon", "rarity": "mythic", "primary": "#ff3bd4", "secondary": "#00f0ff", "desc": "Fogo de plasma salta entre aneis.", "desc_pt": "Fogo de plasma salta entre aneis.", "desc_en": "Plasma fire jumps between rings.", "passive": { "type": "burn", "chance": 0.28, "value": 8, "durationMs": 3800 }, "effects": ["burn"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Bau lendario raro", "unlock_hint_pt": "Bau lendario raro", "sources": ["legendary_chest_rare"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/plasma_dragon.png", "drop_pool": "mythic", "chest_chance": 0.006, "wheel": "monthly" },
	{ "id": "antimatter_core", "name": "Nucleo de Antimateria", "name_pt": "Nucleo de Antimateria", "name_en": "Antimatter Core", "rarity": "mythic", "primary": "#f8fafc", "secondary": "#120017", "desc": "Impactos causam explosoes de antimateria.", "desc_pt": "Impactos causam explosoes de antimateria.", "desc_en": "Impacts cause antimatter bursts.", "passive": { "type": "area_damage", "chance": 0.28, "value": 0.9 }, "effects": ["area_damage"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Roleta mensal", "unlock_hint_pt": "Roleta mensal", "sources": ["monthly_wheel"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/antimatter_core.png", "drop_pool": "mythic", "chest_chance": 0.006, "wheel": "monthly" },
	{ "id": "fractal_moon", "name": "Lua Fractal", "name_pt": "Lua Fractal", "name_en": "Fractal Moon", "rarity": "mythic", "primary": "#d8e8ff", "secondary": "#38bdf8", "desc": "Reduz velocidade de aneis e melhora perfects.", "desc_pt": "Reduz velocidade de aneis e melhora perfects.", "desc_en": "Slows rings and improves perfects.", "passive": { "type": "slow_ring", "chance": 0.24, "value": 0.44, "durationMs": 3000 }, "effects": ["slow_ring"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Conquista de perfects", "unlock_hint_pt": "Conquista de perfects", "sources": ["perfect_achievement"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/fractal_moon.png", "drop_pool": "mythic", "chest_chance": 0.006, "wheel": "monthly" },
	{ "id": "dimensional_comet", "name": "Cometa Dimensional", "name_pt": "Cometa Dimensional", "name_en": "Dimensional Comet", "rarity": "mythic", "primary": "#8b5cf6", "secondary": "#00f0ff", "desc": "Velocidade dimensional com chance de atravessar solido.", "desc_pt": "Velocidade dimensional com chance de atravessar solido.", "desc_en": "Dimensional speed with phase chance.", "passive": { "type": "speed", "value": 0.19 }, "effects": ["speed"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Modo infinito", "unlock_hint_pt": "Modo infinito", "sources": ["infinite_mode"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/dimensional_comet.png", "drop_pool": "mythic", "chest_chance": 0.006, "wheel": "monthly" },
	{ "id": "phantom_crown", "name": "Coroa Fantasma", "name_pt": "Coroa Fantasma", "name_en": "Phantom Crown", "rarity": "mythic", "primary": "#f8fbff", "secondary": "#a855f7", "desc": "Fase espectral com criticos aumentados.", "desc_pt": "Fase espectral com criticos aumentados.", "desc_en": "Spectral phase with increased criticals.", "passive": { "type": "phase_solid", "chance": 0.14, "value": 1 }, "effects": ["phase_solid"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Liga Neon", "unlock_hint_pt": "Liga Neon", "sources": ["neon_league"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/phantom_crown.png", "drop_pool": "mythic", "chest_chance": 0.006, "wheel": "monthly" },
	{ "id": "black_lightning", "name": "Relampago Negro", "name_pt": "Relampago Negro", "name_en": "Black Lightning", "rarity": "mythic", "primary": "#080812", "secondary": "#7c3aed", "desc": "Correntes negras causam impactos criticos.", "desc_pt": "Correntes negras causam impactos criticos.", "desc_en": "Black currents cause critical impacts.", "passive": { "type": "chain_damage", "chance": 0.25, "value": 0.78 }, "effects": ["chain_damage"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Bau lendario raro", "unlock_hint_pt": "Bau lendario raro", "sources": ["legendary_chest_rare"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/black_lightning.png", "drop_pool": "mythic", "chest_chance": 0.006, "wheel": "monthly" },
	{ "id": "cosmic_seed", "name": "Semente Cosmica", "name_pt": "Semente Cosmica", "name_en": "Cosmic Seed", "rarity": "mythic", "primary": "#34ff8c", "secondary": "#7c3aed", "desc": "Cresce com a rodada e aumenta recursos.", "desc_pt": "Cresce com a rodada e aumenta recursos.", "desc_en": "Grows with the run and increases resources.", "passive": { "type": "xp_multiplier", "value": 0.28 }, "effects": ["xp_multiplier"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Missao mensal", "unlock_hint_pt": "Missao mensal", "sources": ["monthly_mission"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/cosmic_seed.png", "drop_pool": "mythic", "chest_chance": 0.006, "wheel": "monthly" },
	{ "id": "control_orb", "name": "Orbe de Controle", "name_pt": "Orbe de Controle", "name_en": "Control Orb", "rarity": "mythic", "primary": "#00f0ff", "secondary": "#ffffff", "desc": "Focada em controle direcional e velocidade.", "desc_pt": "Focada em controle direcional e velocidade.", "desc_en": "Focused on directional control and speed.", "passive": { "type": "speed", "value": 0.18 }, "effects": ["speed", "control"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Roleta mensal, conquista", "unlock_hint_pt": "Roleta mensal, conquista", "sources": ["monthly_wheel", "achievement"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/control_orb.png", "drop_pool": "mythic", "chest_chance": 0.006, "wheel": "monthly" },
	{ "id": "astral_diamond", "name": "Diamante Astral", "name_pt": "Diamante Astral", "name_en": "Astral Diamond", "rarity": "mythic", "primary": "#b8f3ff", "secondary": "#ffffff", "desc": "Perfects podem gerar diamantes extras.", "desc_pt": "Perfects podem gerar diamantes extras.", "desc_en": "Perfects can generate extra diamonds.", "passive": { "type": "perfect_chance", "value": 0.07 }, "effects": ["perfect_chance"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Bau lendario raro", "unlock_hint_pt": "Bau lendario raro", "sources": ["legendary_chest_rare"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/astral_diamond.png", "drop_pool": "mythic", "chest_chance": 0.006, "wheel": "monthly" },
	{ "id": "eclipse_god", "name": "Deus do Eclipse", "name_pt": "Deus do Eclipse", "name_en": "Eclipse God", "rarity": "ultimate", "primary": "#080808", "secondary": "#ffd700", "desc": "Ultimate divina que dobra a gravidade dos aneis e permite controle forte.", "desc_pt": "Ultimate divina que dobra a gravidade dos aneis e permite controle forte.", "desc_en": "A divine ultimate that bends ring gravity and gives strong control.", "passive": { "type": "area_damage", "chance": 0.31, "value": 1.02 }, "effects": ["area_damage", "control"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "50 fases, bau ultimate futuro", "unlock_hint_pt": "50 fases, bau ultimate futuro", "sources": ["50_phases", "future_ultimate_chest"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/eclipse_god.png", "drop_pool": "ultimate", "chest_chance": 0.001, "wheel": "common" },
	{ "id": "multiverse_heart", "name": "Coracao do Multiverso", "name_pt": "Coracao do Multiverso", "name_en": "Multiverse Heart", "rarity": "ultimate", "primary": "#ff4fd8", "secondary": "#00f0ff", "desc": "Pulsa energia de multiplas dimensoes, aumentando criticos, XP e controle.", "desc_pt": "Pulsa energia de multiplas dimensoes, aumentando criticos, XP e controle.", "desc_en": "Pulses multidimensional energy, increasing criticals, XP and control.", "passive": { "type": "cosmic_critical", "chance": 0.28, "value": 0.42 }, "effects": ["cosmic_critical", "control"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Infinito 25 min", "unlock_hint_pt": "Infinito 25 min", "sources": ["infinite_25m"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/multiverse_heart.png", "drop_pool": "ultimate", "chest_chance": 0.001, "wheel": "common" },
	{ "id": "singularity_dragon", "name": "Dragao da Singularidade", "name_pt": "Dragao da Singularidade", "name_en": "Singularity Dragon", "rarity": "ultimate", "primary": "#050008", "secondary": "#ff2d2d", "desc": "Queima e puxa aneis com forca de singularidade.", "desc_pt": "Queima e puxa aneis com forca de singularidade.", "desc_en": "Burns and pulls rings with singularity force.", "passive": { "type": "burn", "chance": 0.34, "value": 9, "durationMs": 4200 }, "effects": ["burn", "control"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Liga Neon rank alto", "unlock_hint_pt": "Liga Neon rank alto", "sources": ["high_neon_league"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/singularity_dragon.png", "drop_pool": "ultimate", "chest_chance": 0.001, "wheel": "common" },
	{ "id": "neon_emperor", "name": "Imperador Neon", "name_pt": "Imperador Neon", "name_en": "Neon Emperor", "rarity": "ultimate", "primary": "#ffd700", "secondary": "#00f0ff", "desc": "Skin imperial da Liga Neon com bonus de moedas, onda real e controle.", "desc_pt": "Skin imperial da Liga Neon com bonus de moedas, onda real e controle.", "desc_en": "Imperial Neon League skin with coin bonus, royal wave and control.", "passive": { "type": "league_king_wave", "chance": 0.2, "value": 0.42 }, "effects": ["league_king_wave", "control"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Recompensa de temporada da Liga Neon", "unlock_hint_pt": "Recompensa de temporada da Liga Neon", "sources": ["league_season_reward"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/neon_emperor.png", "drop_pool": "ultimate", "chest_chance": 0.001, "wheel": "common" },
	{ "id": "void_angel", "name": "Anjo do Vacuo", "name_pt": "Anjo do Vacuo", "name_en": "Void Angel", "rarity": "ultimate", "primary": "#ffffff", "secondary": "#7c3aed", "desc": "Atravessa dimensoes e cria pulsos do vazio.", "desc_pt": "Atravessa dimensoes e cria pulsos do vazio.", "desc_en": "Phases through dimensions and creates void pulses.", "passive": { "type": "phase_solid", "chance": 0.17, "value": 1 }, "effects": ["phase_solid", "control"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Conquista secreta", "unlock_hint_pt": "Conquista secreta", "sources": ["secret_achievement"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/void_angel.png", "drop_pool": "ultimate", "chest_chance": 0.001, "wheel": "common" },
	{ "id": "genesis_core", "name": "Nucleo Genesis", "name_pt": "Nucleo Genesis", "name_en": "Genesis Core", "rarity": "ultimate", "primary": "#fff7ad", "secondary": "#38bdf8", "desc": "Aumenta XP, perfects e da controle avancado.", "desc_pt": "Aumenta XP, perfects e da controle avancado.", "desc_en": "Increases XP, perfects and gives advanced control.", "passive": { "type": "xp_multiplier", "value": 0.36 }, "effects": ["xp_multiplier", "control"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Completar colecao mitica", "unlock_hint_pt": "Completar colecao mitica", "sources": ["mythic_collection"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/genesis_core.png", "drop_pool": "ultimate", "chest_chance": 0.001, "wheel": "common" },
	{ "id": "prismatic_omega", "name": "Omega Prismatico", "name_pt": "Omega Prismatico", "name_en": "Prismatic Omega", "rarity": "ultimate", "primary": "#ffffff", "secondary": "#ff4fd8", "desc": "Ultimate prismatica com bonus geral e controle forte por cargas.", "desc_pt": "Ultimate prismatica com bonus geral e controle forte por cargas.", "desc_en": "Prismatic ultimate with broad bonuses and strong charge control.", "passive": { "type": "all_bonus", "chance": 0.3, "value": 0.28 }, "effects": ["all_bonus", "control"], "trail": "Generated neon trail", "impact": "Generated neon impact", "unlock_hint": "Evento futuro, conquista maxima", "unlock_hint_pt": "Evento futuro, conquista maxima", "sources": ["future_event", "max_achievement"], "origin": "generated_collection_2026_06", "asset_path": "res://assets/skins/generated/prismatic_omega.png", "drop_pool": "ultimate", "chest_chance": 0.001, "wheel": "common" },
]

const SKINS := BASE_SKINS + GENERATED_SKINS

const RUN_UPGRADES := [
	{ "id": "damage", "name": "Dano+", "description": "+15% de dano", "icon": "⚔️", "rarity": "common", "maxLevel": 10, "unlockLevel": 1, "unlockRequirement": "Perfil nível 1", "secret": false, "effects": [{ "type": "damage", "value": 0.15 }] },
	{ "id": "speed", "name": "Velocidade+", "description": "+20% de velocidade", "icon": "⚡", "rarity": "common", "maxLevel": 10, "unlockLevel": 1, "unlockRequirement": "Perfil nível 1", "secret": false, "effects": [{ "type": "speed", "value": 0.2 }] },
	{ "id": "coinBoost", "name": "Chuva de Moedas", "description": "+50% de moedas", "icon": "💰", "rarity": "common", "maxLevel": 10, "unlockLevel": 1, "unlockRequirement": "Perfil nível 1", "secret": false, "effects": [{ "type": "coinMultiplier", "value": 0.5 }] },
	{ "id": "critical", "name": "Crítico+", "description": "+5% chance crítica", "icon": "💥", "rarity": "common", "maxLevel": 8, "unlockLevel": 1, "unlockRequirement": "Perfil nível 1", "secret": false, "effects": [{ "type": "critChance", "value": 5 }] },
	{ "id": "xpBoost", "name": "XP Boost", "description": "+50% de XP", "icon": "⭐", "rarity": "common", "maxLevel": 10, "unlockLevel": 3, "unlockRequirement": "Perfil nível 3", "secret": false, "effects": [{ "type": "xpMultiplier", "value": 0.5 }] },
	{ "id": "bounce", "name": "Ricochete", "description": "+1 ricochete extra", "icon": "🎯", "rarity": "rare", "maxLevel": 5, "unlockLevel": 7, "unlockRequirement": "Perfil nível 7", "secret": false, "effects": [{ "type": "bounce", "value": 1 }] },
	{ "id": "perfectChance", "name": "Perfect Chance", "description": "+1% chance de diamante no Perfect", "icon": "💎", "rarity": "rare", "maxLevel": 7, "unlockLevel": 5, "unlockRequirement": "Perfil nível 5", "secret": false, "effects": [{ "type": "perfectChance", "value": 0.01 }] },
	{ "id": "burn", "name": "Queimar", "description": "Causa dano contínuo de fogo", "icon": "🔥", "rarity": "rare", "maxLevel": 5, "unlockLevel": 5, "unlockRequirement": "Perfil nível 3", "secret": false, "effects": [{ "type": "burn", "value": 10 }] },
	{ "id": "penetration", "name": "Veneno", "description": "Aplica dano progressivo", "icon": "🗡️", "rarity": "rare", "maxLevel": 5, "unlockLevel": 5, "unlockRequirement": "Perfil nível 5", "secret": false, "effects": [{ "type": "poison", "value": 1 }] },
	{ "id": "ricochet", "name": "Ricochete Vivo", "description": "Mais variação e velocidade após impacto", "icon": "🔁", "rarity": "rare", "maxLevel": 5, "unlockLevel": 5, "unlockRequirement": "Perfil nível 7", "secret": false, "effects": [{ "type": "ricochet", "value": 1 }] },
	{ "id": "shockwave", "name": "Onda de Choque", "description": "Dano em área ao impacto", "icon": "🌊", "rarity": "epic", "maxLevel": 5, "unlockLevel": 8, "unlockRequirement": "Perfil nível 12", "secret": false, "effects": [{ "type": "shockwave", "value": 0.5 }] },
	{ "id": "chainLightning", "name": "Raio em Cadeia", "description": "Ataca alvos próximos", "icon": "⚡", "rarity": "epic", "maxLevel": 5, "unlockLevel": 10, "unlockRequirement": "Perfil nível 10", "secret": false, "effects": [{ "type": "chain", "value": 2 }] },
	{ "id": "frost", "name": "Congelamento", "description": "Desacelera anéis", "icon": "❄️", "rarity": "epic", "maxLevel": 5, "unlockLevel": 5, "unlockRequirement": "Perfil nível 5", "secret": false, "effects": [{ "type": "frost", "value": 0.3 }] },
	{ "id": "bomb", "name": "Bomba", "description": "Chance de explosão massiva", "icon": "💣", "rarity": "epic", "maxLevel": 5, "unlockLevel": 15, "unlockRequirement": "Perfil nível 15", "secret": false, "effects": [{ "type": "bomb", "value": 3 }] },
	{ "id": "laser", "name": "Raio Laser", "description": "Dispara raio laser", "icon": "🔫", "rarity": "epic", "maxLevel": 5, "unlockLevel": 12, "unlockRequirement": "Perfil nível 12", "secret": false, "effects": [{ "type": "laser", "value": 50 }] },
	{ "id": "multihit", "name": "Multi-Hit", "description": "Múltiplos ataques simultâneos", "icon": "✨", "rarity": "legendary", "maxLevel": 3, "unlockLevel": 15, "unlockRequirement": "Perfil nível 25", "secret": false, "effects": [{ "type": "multihit", "value": 1 }] },
	{ "id": "slowField", "name": "Slow Field", "description": "Chance de desacelerar todos os anéis", "icon": "🌀", "rarity": "epic", "maxLevel": 5, "unlockLevel": 9, "unlockRequirement": "Perfil nível 9", "secret": false, "effects": [{ "type": "slowField", "value": 0.35 }] },
	{ "id": "ringRepulse", "name": "Ring Repulse", "description": "Empurra o anel atingido para fora", "icon": "↗️", "rarity": "rare", "maxLevel": 5, "unlockLevel": 7, "unlockRequirement": "Perfil nível 7", "secret": false, "effects": [{ "type": "repulse", "value": 18 }] },
	{ "id": "laserCut", "name": "Laser Cut", "description": "Chance de dano alto no anel", "icon": "🔦", "rarity": "epic", "maxLevel": 5, "unlockLevel": 12, "unlockRequirement": "Perfil nível 12", "secret": false, "effects": [{ "type": "laserCut", "value": 2.5 }] },
	{ "id": "chainBreak", "name": "Chain Break", "description": "Quebrar um anel fere o próximo", "icon": "⛓️", "rarity": "legendary", "maxLevel": 4, "unlockLevel": 18, "unlockRequirement": "Perfil nível 18", "secret": false, "effects": [{ "type": "chainBreak", "value": 0.35 }] },
	{ "id": "shieldPulse", "name": "Shield Pulse", "description": "Escudo curto contra esmagamento", "icon": "🛡️", "rarity": "epic", "maxLevel": 4, "unlockLevel": 14, "unlockRequirement": "Perfil nível 14", "secret": false, "effects": [{ "type": "shield", "value": 2 }] },
	{ "id": "timeFreeze", "name": "Time Freeze", "description": "Congela todos os anéis por pouco tempo", "icon": "⏱️", "rarity": "legendary", "maxLevel": 3, "unlockLevel": 20, "unlockRequirement": "Perfil nível 20", "secret": false, "effects": [{ "type": "timeFreeze", "value": 1 }] },
	{ "id": "magnetCoins", "name": "Magnet Coins", "description": "Aumenta moedas da rodada", "icon": "🧲", "rarity": "rare", "maxLevel": 8, "unlockLevel": 6, "unlockRequirement": "Perfil nível 6", "secret": false, "effects": [{ "type": "coinMultiplier", "value": 0.25 }] },
	{ "id": "criticalOverload", "name": "Critical Overload", "description": "Críticos acumulam dano temporário", "icon": "💢", "rarity": "legendary", "maxLevel": 4, "unlockLevel": 16, "unlockRequirement": "Perfil nível 16", "secret": false, "effects": [{ "type": "critOverload", "value": 0.3 }] },
	{ "id": "chronoBreak", "name": "Chrono Break", "description": "Pequena chance de congelar todos os anéis por alguns segundos.", "icon": "⏳", "rarity": "legendary", "maxLevel": 3, "unlockLevel": 1, "unlockRequirement": "Conquista secreta", "secret": true, "effects": [{ "type": "timeFreeze", "value": 1 }] },
	{ "id": "voidPulse", "name": "Void Pulse", "description": "Chance de causar dano em área ao quebrar um anel.", "icon": "🌑", "rarity": "legendary", "maxLevel": 4, "unlockLevel": 1, "unlockRequirement": "Conquista secreta", "secret": true, "effects": [{ "type": "areaDamage", "value": 0.45 }] },
	{ "id": "diamondInstinct", "name": "Diamond Instinct", "description": "Aumenta chance de diamante em Perfect Escape.", "icon": "💠", "rarity": "epic", "maxLevel": 4, "unlockLevel": 1, "unlockRequirement": "Conquista secreta", "secret": true, "effects": [{ "type": "perfectChance", "value": 0.018 }] },
	{ "id": "comboOverdrive", "name": "Combo Overdrive", "description": "Combos altos aumentam dano e moedas temporariamente.", "icon": "🚀", "rarity": "legendary", "maxLevel": 3, "unlockLevel": 1, "unlockRequirement": "Conquista secreta", "secret": true, "effects": [{ "type": "comboBoost", "value": 0.25 }] },
	{ "id": "lastShield", "name": "Last Shield", "description": "Uma vez por partida, evita morte por esmagamento.", "icon": "🛡️", "rarity": "legendary", "maxLevel": 2, "unlockLevel": 1, "unlockRequirement": "Conquista secreta", "secret": true, "effects": [{ "type": "lastShield", "value": 1 }] },
	{ "id": "royalBreaker", "name": "Royal Breaker", "description": "Aumenta dano contra anéis externos.", "icon": "👑", "rarity": "legendary", "maxLevel": 4, "unlockLevel": 1, "unlockRequirement": "Conquista secreta", "secret": true, "effects": [{ "type": "outerDamage", "value": 0.22 }] },
	{ "id": "bossHunter", "name": "Boss Hunter", "description": "Aumenta dano e XP em modos competitivos.", "icon": "🎯", "rarity": "epic", "maxLevel": 4, "unlockLevel": 1, "unlockRequirement": "Conquista secreta", "secret": true, "effects": [{ "type": "competitiveBoost", "value": 0.18 }] },
	{ "id": "secretMagnet", "name": "Secret Magnet", "description": "Aumenta moedas gerais recebidas no final.", "icon": "🧲", "rarity": "epic", "maxLevel": 5, "unlockLevel": 1, "unlockRequirement": "Conquista secreta", "secret": true, "effects": [{ "type": "coinMultiplier", "value": 0.18 }] },
	{ "id": "trophyInstinct", "name": "Trophy Instinct", "description": "Pequeno bônus de troféus ao vencer competições.", "icon": "🏆", "rarity": "epic", "maxLevel": 3, "unlockLevel": 1, "unlockRequirement": "Conquista secreta", "secret": true, "effects": [{ "type": "trophyBonus", "value": 2 }] },
	{ "id": "rivalCrusher", "name": "Rival Crusher", "description": "Aumenta dano e XP em partidas competitivas.", "icon": "💢", "rarity": "legendary", "maxLevel": 3, "unlockLevel": 1, "unlockRequirement": "Conquista secreta", "secret": true, "effects": [{ "type": "competitiveBoost", "value": 0.24 }] },
]

const AUTO_RUN_UPGRADE_IDS := [
	"damage",
	"speed",
	"coinBoost",
	"critical",
	"xpBoost",
	"perfectChance",
]

const LEAGUE_RANKS := [
	{ "id": "bronze", "name": "Bronze", "min": 0, "reward": { "type": "coins", "amount": 300 } },
	{ "id": "silver", "name": "Prata", "min": 300, "reward": { "type": "diamonds", "amount": 18 } },
	{ "id": "gold", "name": "Ouro", "min": 700, "reward": { "type": "keys", "amount": 1 } },
	{ "id": "diamond", "name": "Diamante", "min": 1200, "reward": { "type": "chest", "chest_type": "rare", "amount": 1 } },
	{ "id": "legendary", "name": "Lendário", "min": 1900, "reward": { "type": "legendaryKeys", "amount": 1 } },
	{ "id": "ultimate", "name": "Ultimate", "min": 2800, "reward": { "type": "skin", "skin_id": "league_king_neon" } },
]

const LEAGUE_TOP_SKINS := [
	"neon_emperor",
	"control_orb",
	"void_eye",
	"obsidian_sentinel",
	"blue_flame",
]

const LEAGUE_BOT_SKINS := [
	"divine_core",
	"living_singularity",
	"eclipse_god",
	"multiverse_heart",
	"singularity_dragon",
	"void_angel",
	"genesis_core",
	"prismatic_omega",
	"chronal_orb",
	"ether_guardian",
	"control_orb",
	"infinite_vortex_mythic",
	"chrono_loop_mythic",
	"void_eye",
	"living_star",
	"plasma_dragon",
	"cosmic_fragment",
	"eternal_core",
	"endless_prism",
	"neon_eclipse",
	"league_bronze_champion",
	"astral_dragon",
	"solar_guardian",
	"black_sun",
	"blue_vortex",
	"red_comet",
	"fire",
	"ice",
	"lightning",
	"crystal",
	"wolf_rare",
	"robot",
]

const CONTROL_SKIN_IDS := [
	"robot",
	"alien_rare",
	"ninja_rare",
	"satellite_rare",
	"blue_vortex",
	"neon_spiral",
	"ripple_eye",
	"celestial_core",
	"chrono_loop_mythic",
	"divine_core",
]

const CONTROL_STRENGTH_BY_RARITY := {
	"common": 0.13,
	"rare": 0.24,
	"epic": 0.34,
	"legendary": 0.48,
	"mythic": 0.62,
	"ultimate": 0.80,
}

func skin_by_id(id: String) -> Dictionary:
	for skin in SKINS:
		if String(skin.get("id", "")) == id:
			return skin
	return {}

func skin_has_control(id: String) -> bool:
	if CONTROL_SKIN_IDS.has(id.to_lower()):
		return true
	var skin := skin_by_id(id)
	if skin.is_empty():
		return false
	if String(skin.get("rarity", "common")) == "ultimate":
		return true
	for effect in Array(skin.get("effects", [])):
		if String(effect).to_lower() in ["control", "controle"]:
			return true
	return false

func skin_control_strength(id: String) -> float:
	var skin := skin_by_id(id)
	var rarity := String(skin.get("rarity", "common")) if not skin.is_empty() else "common"
	return float(CONTROL_STRENGTH_BY_RARITY.get(rarity, 0.13))

func skin_asset_path(id: String) -> String:
	var skin := skin_by_id(id)
	var declared := String(skin.get("asset_path", "")) if not skin.is_empty() else ""
	if not declared.is_empty() and ResourceLoader.exists(declared):
		return declared
	var direct := "res://assets/skins/%s.png" % id
	if ResourceLoader.exists(direct):
		return direct
	var generated := "res://assets/skins/generated/%s.png" % id
	if ResourceLoader.exists(generated):
		return generated
	return "res://assets/skins/neon_blue.png"

func upgrade_by_id(id: String) -> Dictionary:
	for upgrade in RUN_UPGRADES:
		if String(upgrade.get("id", "")) == id:
			return upgrade
	return {}

func run_upgrades() -> Array[Dictionary]:
	var result: Array[Dictionary] = []
	for upgrade in RUN_UPGRADES:
		result.append(Dictionary(upgrade).duplicate(true))
	return result

func all_run_upgrade_ids() -> Array[String]:
	var result: Array[String] = []
	for upgrade in RUN_UPGRADES:
		var id := String(upgrade.get("id", ""))
		if not id.is_empty():
			result.append(id)
	return result

func released_run_upgrade_ids() -> Array[String]:
	var result: Array[String] = []
	for upgrade in RUN_UPGRADES:
		var id := String(upgrade.get("id", ""))
		if not id.is_empty() and not bool(upgrade.get("secret", false)):
			result.append(id)
	return result

func auto_run_upgrade_ids() -> Array[String]:
	var result: Array[String] = []
	for id in AUTO_RUN_UPGRADE_IDS:
		result.append(String(id))
	return result

func is_released_run_upgrade(id: String) -> bool:
	return released_run_upgrade_ids().has(id)

func is_run_upgrade_defined(id: String) -> bool:
	return all_run_upgrade_ids().has(id)

func released_run_upgrades() -> Array[Dictionary]:
	var result: Array[Dictionary] = []
	for id in released_run_upgrade_ids():
		var upgrade := upgrade_by_id(id)
		if not upgrade.is_empty():
			result.append(upgrade)
	return result

func rank_for_trophies(trophies: int) -> Dictionary:
	var current := LEAGUE_RANKS[0]
	for rank in LEAGUE_RANKS:
		if trophies >= int(rank.get("min", 0)):
			current = rank
	return current

func league_skin_id_for_position(position: int, seed: int = 0) -> String:
	if position >= 0 and position < LEAGUE_TOP_SKINS.size():
		return String(LEAGUE_TOP_SKINS[position])
	var pool_index: int = abs(position + seed) % LEAGUE_BOT_SKINS.size()
	return String(LEAGUE_BOT_SKINS[pool_index])

func league_skin_for_position(position: int, seed: int = 0) -> Dictionary:
	return skin_by_id(league_skin_id_for_position(position, seed))

func opponent_name(index: int, rank_id: String) -> String:
	var prefixes: Array[String] = ["Nova", "Pixel", "Orbit", "Cyber", "Vortex", "Pulse", "Chrome", "Solar", "Astral", "Rift", "Neon", "Hyper", "Lunar", "Ion", "Prism", "Echo", "Vector", "Zero", "Turbo", "Comet"]
	var suffixes: Array[String] = ["Runner", "Breaker", "Drifter", "Spark", "Core", "Pilot", "Blade", "Rush", "Echo", "Flux", "Prime", "Wave", "Byte", "Ray", "Loop", "Shift", "Dash", "Glider", "Striker", "Orbit"]
	var aliases: Array[String] = ["Astra", "Kiro", "Mika", "Zane", "Lyra", "Noah", "Riven", "Kai", "Nix", "Sol", "Vega", "Ari", "Taro", "Lumi", "Iris", "Axel", "Rafa", "Milo", "Luna", "Theo"]
	var seed: int = abs(("%s_%s" % [rank_id, index]).hash())
	if seed % 5 == 0:
		return "%s %s" % [aliases[seed % aliases.size()], suffixes[(seed / 7) % suffixes.size()]]
	if seed % 4 == 0:
		return "%s %s" % [prefixes[(seed / 3) % prefixes.size()], aliases[(seed / 11) % aliases.size()]]
	return "%s %s" % [prefixes[seed % prefixes.size()], suffixes[(seed / prefixes.size()) % suffixes.size()]]

func opponent_for(trophies: int) -> Dictionary:
	var rank: Dictionary = rank_for_trophies(trophies)
	var seed: int = int(Time.get_unix_time_from_system() / 60) + trophies * 17
	var idx: int = abs(seed) % 200
	var rank_index: int = LEAGUE_RANKS.find(rank)
	var skin_position: int = 5 + max(0, 5 - rank_index) + idx % LEAGUE_BOT_SKINS.size()
	return { "id": "%s_%03d" % [String(rank.get("id", "bronze")), idx], "name": opponent_name(idx, String(rank.get("id", "bronze"))), "rank": rank, "quality": clampf(0.32 + float(rank_index) * 0.1 + float(idx % 17) / 100.0, 0.32, 0.92), "skin": league_skin_for_position(skin_position, idx) }
